### ISSUE TITLE
Panic

### ISSUE THREAD

**Issue by carlosho17** [Consensys-Incorporated/quorum#1108] opened 2020-12-22 09:32 UTC
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: 1.9.7-stable

OS & Version: Ubuntu 16.04.7 LTS 
16G RAM  - inside docker

Branch, Commit Hash or Release: af7525189f2cee801ef6673d438b8577c8c5aa34

#### Backtrace

````
DEBUG[12-15|10:37:59.847] Reset ancient limit to zero
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xca6913]

goroutine 286 [running]:
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestor(0xc000e8d180, 0xc00161e3c0, 0xc0594aefc0, 0x0, 0x0, 0xa)
        /tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:890 +0x14d3
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc000e8d180, 0xc00161e3c0, 0x5be8b18537b8ced6, 0x6e63d297fbd1810, 0x8ba3e9ad36a9fbb0, 0x133e551934bedb65, 0xc027c754c0, 0x0, 0x0)
        /tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:456 +0x3df
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0xc000e8d180, 0xc025329b80, 0x10, 0x5be8b18537b8ced6, 0x6e63d297fbd1810, 0x8ba3e9ad36a9fbb0, 0x133e551934bedb65, 0xc027c754c0, 0x0, 0x0, ...)
        /tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:424 +0x418
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0xc000e8d180, 0xc025329b80, 0x10, 0x5be8b18537b8ced6, 0x6e63d297fbd1810, 0x8ba3e9ad36a9fbb0, 0x133e551934bedb65, 0xc027c754c0, 0x0, 0x0, ...)
        /tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:328 +0x8e
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).synchronise(0xc0002fde00, 0xc00b5160c0)
        /tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:199 +0x2ee
created by github.com/ethereum/go-ethereum/eth.(*ProtocolManager).syncer
        /tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:152 +0x2e5

````

**Comment by carlosho17** [comment] 2020-12-22 10:35
Geth
```
Version: 1.9.7-stable
Git Commit: af7525189f2cee801ef6673d438b8577c8c5aa34
Quorum Version: 20.10.0
Architecture: amd64
Protocol Versions: [64 63]
Network Id: 1337
Go Version: go1.15.2
Operating System: linux
GOPATH=/root/alastria/workspace
GOROOT=/usr/local/go
```

Compiled on Ubuntu 16.04 with Go 1.15.2 


Here's a TRACE previous to the panic

```
TRACE[12-22|10:30:54.220] Accepted connection                      addr=15.188.50.193:36056
TRACE[12-22|10:30:54.223] Quorum permissioning                     id=4ea6934a38bf4901 addr=15.188.50.193:36056             conn=inbound    EnableNodePermission=true DataDir=/root/alastria/data Current Node ID=1f98688cd11041bceba382fd552dcfab9c020c1afb98fd40be86de5a281f6f30 Node Name=Geth/BOT_Planisys_Telsius_8_16_01/v1.9.7-stable-af752518(quorum-v20.10.0)/linux-amd64/go1.15.2 Dialed Dest=nil Connection ID=4ea6934a38bf4901 Connection String=4ea6934a38bf490181a8142f832c55e5365c92f80408308a11db4fe61fca9bc7
TRACE[12-22|10:30:54.223] Node Permissioning is Enabled.           id=4ea6934a38bf4901 addr=15.188.50.193:36056             conn=inbound
TRACE[12-22|10:30:54.239] Connection set up                        id=4ea6934a38bf4901 addr=15.188.50.193:36056             conn=inbound    inbound=true
TRACE[12-22|10:30:54.239] Starting protocol istanbul/64            id=4ea6934a38bf4901 conn=inbound
TRACE[12-22|10:30:54.249] Filtering headers                        peer=ba2fae519ca24b1e headers=1
TRACE[12-22|10:30:54.253] Registering sync peer                    peer=4ea6934a38bf4901
TRACE[12-22|10:30:54.276] Filtering headers                        peer=ba2fae519ca24b1e headers=1
TRACE[12-22|10:30:54.305] Filtering headers                        peer=ba2fae519ca24b1e headers=1
TRACE[12-22|10:30:54.337] Filtering headers                        peer=ba2fae519ca24b1e headers=1
TRACE[12-22|10:30:54.366] Filtering headers                        peer=ba2fae519ca24b1e headers=1
TRACE[12-22|10:30:54.369] Failed RLPx handshake                    addr=195.55.232.91:21000             conn=staticdial err="unexpected EOF"
TRACE[12-22|10:30:54.369] Setting up connection failed             addr=195.55.232.91:21000             err="unexpected EOF"
TRACE[12-22|10:30:54.369] Dial error                               task="staticdial c70fb73bdc78a7c5 195.55.232.91:21000" err="unexpected EOF"
TRACE[12-22|10:30:54.369] Dial task done                           task="staticdial c70fb73bdc78a7c5 195.55.232.91:21000"
TRACE[12-22|10:30:54.369] New dial task                            task="staticdial 11b76f097d35f64d 52.50.15.212:21000"
TRACE[12-22|10:30:54.387] Dial error                               task="staticdial 11b76f097d35f64d 52.50.15.212:21000" err="dial tcp 52.50.15.212:21000: connect: connection refused"
TRACE[12-22|10:30:54.387] Dial task done                           task="staticdial 11b76f097d35f64d 52.50.15.212:21000"
TRACE[12-22|10:30:54.387] New dial task                            task="staticdial 3d05e1428c5fed35 52.28.115.198:21000"
TRACE[12-22|10:30:54.415] Failed RLPx handshake                    addr=52.28.115.198:21000             conn=staticdial err=EOF
TRACE[12-22|10:30:54.415] Setting up connection failed             addr=52.28.115.198:21000             err=EOF
TRACE[12-22|10:30:54.415] Dial error                               task="staticdial 3d05e1428c5fed35 52.28.115.198:21000" err=EOF
TRACE[12-22|10:30:54.415] Dial task done                           task="staticdial 3d05e1428c5fed35 52.28.115.198:21000"
TRACE[12-22|10:30:54.415] New dial task                            task="staticdial 96920153839e0b22 34.252.181.146:21000"
TRACE[12-22|10:30:54.416] Filtering headers                        peer=ba2fae519ca24b1e headers=1
TRACE[12-22|10:30:54.444] Filtering headers                        peer=ba2fae519ca24b1e headers=1
TRACE[12-22|10:30:54.463] Filtering headers                        peer=ba2fae519ca24b1e headers=1
TRACE[12-22|10:30:54.506] Filtering headers                        peer=ba2fae519ca24b1e headers=1
TRACE[12-22|10:30:54.516] Filtering headers                        peer=ba2fae519ca24b1e headers=1
TRACE[12-22|10:30:54.530] Filtering headers                        peer=ba2fae519ca24b1e headers=1
TRACE[12-22|10:30:54.550] Filtering headers                        peer=ba2fae519ca24b1e headers=1
TRACE[12-22|10:30:54.558] Filtering headers                        peer=ba2fae519ca24b1e headers=1
TRACE[12-22|10:30:54.577] Filtering headers                        peer=ba2fae519ca24b1e headers=1
TRACE[12-22|10:30:54.590] Filtering headers                        peer=ba2fae519ca24b1e headers=1
TRACE[12-22|10:30:54.598] Filtering headers                        peer=ba2fae519ca24b1e headers=1
TRACE[12-22|10:30:54.606] Filtering headers                        peer=ba2fae519ca24b1e headers=1

```

**Comment by carlosho17** [comment] 2020-12-22 10:36
Just to make it clear, geth would start and consistently panic after a few seconds.

**Comment by amalrajmani** [comment] 2020-12-22 15:22
hi @carlosho17 
Can you share more details about your network so that I can try to reproduce it.

1. What consensus are you using?
2. What is the genesis config?
3. How many nodes are there?
4. When does this panic occur?
5. Steps to reproduce this issue.

**Comment by ksivane** [comment] 2020-12-26 09:45
Had the same issue when running in Kubernetes. 

Found my container's default resource limits were too low (250MB/0.2core). Increasing to 2GB/0.5core solved it for me.

**Comment by nmvalera** [comment] 2021-01-04 13:45
@carlosho17 I see that you are compiling with go1.15.2 could you please compile with go1.13 and retry? 

Alternatively, instead of compiling yourself, I recommend that you use either
- Official GoQuorum binary distribution on Bintray: https://bintray.com/quorumengineering/quorum/download_file?file_path=v20.10.0/geth_v20.10.0_linux_amd64.tar.gz
- Official docker images: https://hub.docker.com/r/quorumengineering/quorum

Thanks

**Comment by carlosho17** [comment] 2021-01-04 14:20
Hi Nicolas

I've tried now as suggested with go1.13 , but it's still breaking, now
it doesn't seem to recognize our genesis.json, and doesn't like
static-nodes.json (this is a bootnode, so I have to periodically refresh
this with new nodes)


INFO [01-04|14:15:23.416] Starting pprof server                   
addr=http://0.0.0.0:9545/debug/pprof
INFO [01-04|14:15:23.418] Enabling metrics collection
INFO [01-04|14:15:23.418] Enabling metrics export to InfluxDB
INFO [01-04|14:15:23.421] Maximum peer count                      
ETH=200 LES=0 total=200
INFO [01-04|14:15:23.421] Smartcard socket not found, disabling   
err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [01-04|14:15:23.421] permission-config.json file is missing.
Smart-contract-based permission service will be disabled error="stat
/root/alastria/data/permission-config.json: no such file or directory"
WARN [01-04|14:15:23.422] Found deprecated node list file
/root/alastria/data/static-nodes.json, please use the TOML config file
instead.
INFO [01-04|14:15:23.466] Starting peer-to-peer node              
instance=Geth/BOT_Planisys_Telsius_8_16_01/v1.9.7-stable-af752518(quorum-v20.10.0)/linux-amd64/go1.13.2
INFO [01-04|14:15:23.466] Allocated trie memory caches            
clean=2.00MiB dirty=2.00MiB
INFO [01-04|14:15:23.466] Allocated cache and file handles        
database=/root/alastria/data/geth/chaindata cache=16.00MiB handles=524288
INFO [01-04|14:15:23.511] Opened ancient database                 
database=/root/alastria/data/geth/chaindata/ancient
INFO [01-04|14:15:23.514] Initialised chain configuration         
config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true
EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000
IsQuorum: false Constantinople: 7280000 TransactionSizeLimit: 0
MaxCodeSize: 0 Petersburg: 7280000 Istanbul: 9069000
PrivacyEnhancements: <nil> Engine: ethash}"
WARN [01-04|14:15:23.514] Ethash used in full fake mode
INFO [01-04|14:15:23.514] Initialising Ethereum protocol          
name=eth versions="[64 63]" network=83584648538 dbversion=7
INFO [01-04|14:15:23.535] Loaded most recent local header         
number=0 hash=d4e567<E2><80><A6>cb8fa3 td=17179869184 age=51y9mo1d
INFO [01-04|14:15:23.535] Loaded most recent local full blthis ock     
number=0 hash=d4e567<E2><80><A6>cb8fa3 td=17179869184 age=51y9mo1d
INFO [01-04|14:15:23.536] Loaded most recent local fast block     
number=0 hash=d4e567<E2><80><A6>cb8fa3 td=17179869184 age=51y9mo1d
INFO [01-04|14:15:23.536] Loaded local transaction journal        
transactions=0 dropped=0
INFO [01-04|14:15:23.537] Regenerated local transaction journal   
transactions=0 accounts=0
INFO [01-04|14:15:23.538] Allocated fast sync bloom               
size=4.00MiB
INFO [01-04|14:15:23.606] Stats daemon started
INFO [01-04|14:15:23.609] New local node record                    seq=4
id=4a906bb23f4444f9 ip=127.0.0.1 udp=0 tcp=21000
INFO [01-04|14:15:23.609] Started P2P networking                  
self="enode://b4a2ede1a5120a4a2d064b7da126a806c1261969e138c2079d4023cbaca150026a462f19e2a12d0233ee630521b4f4082f93c636f390caa2d10726674a4b6e17@127.0.0.1:21000?discport=0"
INFO [01-04|14:15:23.620] IPC endpoint opened                     
url=/root/alastria/data/geth.ipc
WARN [01-04|14:15:23.621] permission-config.json file is missing.
Smart-contract-based permission service will be disabled error="stat
/root/alastria/data/permission-config.json: no such file or directory"
Fatal: Consensus not specified. Exiting!!

genesis.json we're using since a long time ago

{
  "alloc": {
    "0x58b8527743f89389b754c63489262fdfc9ba9db6": {
      "balance": "1000000000000000000000000000"
    }
  },
  "coinbase": "0x0000000000000000000000000000000000000000",
  "config": {
    "chainId": 83584648538,
    "byzantiumBlock": 0,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip150Hash":
"0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 0,
    "eip158Block": 0,
    "istanbul": {
      "epoch": 30000,
      "policy": 0
    },
    "isQuorum": true
  },
  "extraData":
"0x0000000000000000000000000000000000000000000000000000000000000000f85ad594b87dc349944cc47474775dde627a8a171fc94532b8410000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0",
  "gasLimit": "0x2FEFD800",
  "difficulty": "0x1",
  "mixHash":
"0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
  "nonce": "0x0",
  "parentHash":
"0x0000000000000000000000000000000000000000000000000000000000000000",
  "timestamp": "0x00"
}

**Comment by nmvalera** [comment] 2021-01-04 14:31
Could you please share the `geth` command you are running?

**Comment by carlosho17** [comment] 2021-01-04 14:40
geth --datadir /root/alastria/data --networkid 83584648538 --identity
BOT_Planisys_Telsius_8_16_01 --permissioned --port 21000 --ethstats
BOT_Planisys_Telsius_8_16_01:bb98a0b6442386d0cdf8a31b267892c1@netstats.telsius.alastria.io:80
--targetgaslimit 8000000 --syncmode fast --nodiscover --metrics
--metrics.expensive --pprof --pprofaddr 0.0.0.0 --pprofport 9545
--metrics.influxdb --metrics.influxdb.endpoint
http://geth-metrics.planisys.net:8086 --metrics.influxdb.database
alastria --metrics.influxdb.username alastriausr
--metrics.influxdb.password EDITED --metrics.influxdb.tags
host=BOT_Planisys_Telsius_8_16_01 --verbosity 3 --cache 10 --nousb
--maxpeers 200

**Comment by nmvalera** [comment] 2021-01-04 14:43
What consensus are you using?

**Comment by carlosho17** [comment] 2021-01-04 14:46
AFAIK Ibft1

**Comment by SatpalSandhu61** [comment] 2021-01-04 15:15
Did you re-init the geth directory? If so, are you positive that is the genesis file you used (and that it's not corrupted in any way)?
I would only expect to see the `Consensus not specified` error if the `"istanbul"` block was missing from the genesis file.

[You can ignore the `Found deprecated node list file /root/alastria/data/static-nodes.json, please use the TOML config file
instead.` warning in the logs. The static-node.json is still being parsed correctly.]

**Comment by carlosho17** [comment] 2021-01-04 15:35
Hi,

yes I've reset the geth directory trying to resync from the beginning.

If I switch back to the prior non-empty chaindata (including the ancient
subdirectory), I get another error message.

It might be slightly different from the one I posted at the beginning of
the issue, because now geth has been compiled with go1.13.2 as per your
request.

````
INFO [01-04|15:32:26.240] Block synchronisation started
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xc6b5dc]

goroutine 252 [running]:
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestor(0xc002c18380,
0xc002f48000, 0xc001761200, 0x0, 0x0, 0xa)
       
/tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:890
+0x144c
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc002c18380,
0xc002f48000, 0xb48423df038ee5b7, 0xbd4a57cf7d2be258,
0xa1b223526ecbd9b7, 0xb6cbf4eeb55432c0, 0xc003114fc0, 0x0, 0x0)
       
/tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:456
+0x3f0
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0xc002c18380,
0xc002a24600, 0x10, 0xb48423df038ee5b7, 0xbd4a57cf7d2be258,
0xa1b223526ecbd9b7, 0xb6cbf4eeb55432c0, 0xc003114fc0, 0x0, 0x0, ...)
       
/tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:424
+0x43b
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0xc002c18380,
0xc002a24600, 0x10, 0xb48423df038ee5b7, 0xbd4a57cf7d2be258,
0xa1b223526ecbd9b7, 0xb6cbf4eeb55432c0, 0xc003114fc0, 0x0,
0x512e704488e2a701, ...)
       
/tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:328
+0x8e
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).synchronise(0xc002c70c30,
0xc002b98000)
       
/tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:199
+0x2dd
created by github.com/ethereum/go-ethereum/eth.(*ProtocolManager).syncer
       
/tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:152
+0x2e6
````

**Comment by carlosho17** [comment] 2021-01-04 15:43
This is all under docker 

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.7 LTS"


````
Geth
Version: 1.9.7-stable
Git Commit: af7525189f2cee801ef6673d438b8577c8c5aa34
Quorum Version: 20.10.0
Architecture: amd64
Protocol Versions: [64 63]
Network Id: 1337
Go Version: go1.13.2
Operating System: linux
GOPATH=/root/alastria/workspace
GOROOT=/usr/local/go
````

Of course I could try your official packages and  Ubuntu 18.04 ... I just need to figure out how to reinstall without changing the e-node , as this is a script-based installation standard of the Alastria network.

**Comment by SatpalSandhu61** [comment] 2021-01-04 15:48
Ok. I suspect the issue with the original geth data directory is a db corruption, so you are doing the correct thing by resetting the geth directory.

However, there appears to be an issue with the genesis file that you used to perform the `geth init`. Please double-check that you used the correct genesis.json. Or you can try resetting the data directory again - if it still fails then pls attach the actual genesis file to this ticket.

I think the build you are using is probably fine, but if you are able to use the official packages then it will eliminate any potential build issues.

**Comment by carlosho17** [comment] 2021-01-04 15:50
sorry @amalrajmani I hadn't seen your questions. I think most of them have been answered so far, static-nodes.json contains 176 nodes.

**Comment by carlosho17** [comment] 2021-01-04 17:40
geth keeps crashing when using https://bintray.com/quorumengineering/quorum/download_file?file_path=v20.10.0/geth_v20.10.0_linux_amd64.tar.gz:

````
INFO [01-04|17:38:06.869] Block synchronisation started
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xc6b9bc]

goroutine 310 [running]:
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestor(0xc002b8a380, 0xc000d324b0, 0xc00291c240, 0x0, 0x0, 0xa)
        /home/runner/work/quorum/quorum/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:890 +0x144c
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc002b8a380, 0xc000d324b0, 0x162a6069e1a2aab5, 0xdca0568a696767d1, 0x56157f125f440a2, 0x21919286a2c0bb95, 0xc003648600, 0x0, 0x0)
        /home/runner/work/quorum/quorum/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:456 +0x3f0
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0xc002b8a380, 0xc000f31c40, 0x10, 0x162a6069e1a2aab5, 0xdca0568a696767d1, 0x56157f125f440a2, 0x21919286a2c0bb95, 0xc003648600, 0x0, 0x0, ...)
        /home/runner/work/quorum/quorum/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:424 +0x43b
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0xc002b8a380, 0xc000f31c40, 0x10, 0x162a6069e1a2aab5, 0xdca0568a696767d1, 0x56157f125f440a2, 0x21919286a2c0bb95, 0xc003648600, 0x0, 0x0, ...)
        /home/runner/work/quorum/quorum/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:328 +0x8e
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).synchronise(0xc002b8d680, 0xc00237c000)
        /home/runner/work/quorum/quorum/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:199 +0x2dd
created by github.com/ethereum/go-ethereum/eth.(*ProtocolManager).syncer
        /home/runner/work/quorum/quorum/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:152 +0x2e6

````

**Comment by carlosho17** [comment] 2021-01-04 17:57
I tried brutally reducing the number of permissioned nodes from 178 to 50 or so , and tried restarting many times just to let the bootnode make an attempt to sync , and in all cases I found similar lines before dying:

````
DEBUG[01-04|17:53:21.564] **Fetching batch of headers**                id=0a589b3dde331f5b conn=staticdial count=1  fromnum=56518581 skip=0  reverse=false
DEBUG[01-04|17:53:21.594] **Discarded propagated block, too far away peer**=ded3a96b3b20332b number=58786080 hash=6cc172…47d685 distance=3843000
TRACE[01-04|17:53:21.595] Filtering headers                        peer=0a589b3dde331f5b headers=1
DEBUG[01-04|17:53:21.596] Synchronisation terminated               elapsed=858.541ms
DEBUG[01-04|17:53:21.596] **Reset ancient limit to zero**
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xc6b9bc]
````

**Comment by carlosho17** [comment] 2021-01-04 19:33
Hi
just initialized a geth directory with 
````
geth --datadir ~/alastria/data init ~/alastria-node/data/genesis.json
````
and geth binary downloaded from Consensys' repo

The bootnode doesn't synchronize , neither with syncmode **fast** nor **full**

It shows up in the statistics with 0 peers

And these sequence of messages show up for all permissioned node IP addresses


````
TRACE[01-04|19:30:54.504] New dial task                            task="staticdial ca9a54929ccbcdcd 185.180.10.170:21000"
TRACE[01-04|19:30:54.514] Quorum permissioning                     id=ca9a54929ccbcdcd addr=185.180.10.170:21000            conn=staticdial EnableNodePermission=true DataDir=/root/alastria/data Current Node ID=f6296938f06cfda70e0021ddd4bb4bb6d5115ba0e35e8b4b6212a105e8a34273 Node Name=Geth/BOT_Planisys_Telsius_8_16_01/v1.9.7-stable-af752518(quorum-v20.10.0)/linux-amd64/go1.13.15 Dialed Dest="enode://59b4a8f81b10f3206401fea5a6cef9ea51966b26625133c13aaffefa36fc180562633079b5b0f079f35e7e9ff3fde740431511f0b188a925a9aeb8bbd2888164@185.180.10.170:21000?discport=0" Connection ID=ca9a54929ccbcdcd Connection String=ca9a54929ccbcdcdcb26519daa5263e47b61fcfbade60b68af5cd625ab583a6e
TRACE[01-04|19:30:54.514] Node Permissioning is Enabled.           id=ca9a54929ccbcdcd addr=185.180.10.170:21000            conn=staticdial
TRACE[01-04|19:30:54.554] Failed proto handshake                   id=ca9a54929ccbcdcd addr=185.180.10.170:21000            conn=staticdial err=EOF
TRACE[01-04|19:30:54.554] Setting up connection failed             addr=185.180.10.170:21000            err=EOF
TRACE[01-04|19:30:54.554] Dial error                               task="staticdial ca9a54929ccbcdcd 185.180.10.170:21000" err=EOF
TRACE[01-04|19:30:54.554] Dial task done                           task="staticdial ca9a54929ccbcdcd 185.180.10.170:21000"
TRACE[01-04|19:31:15.398] Accepted connection                      addr=185.180.10.170:41624
TRACE[01-04|19:31:15.402] Failed RLPx handshake                    addr=185.180.10.170:41624            conn=inbound    err="ecies: invalid message"
TRACE[01-04|19:31:15.402] Setting up connection failed             addr=185.180.10.170:41624            err="ecies: invalid message"

````
The 185.180.10.170 node happens to be a 20.10.0 too , but it's the same with all IP addresses of permissioned nodes

**Comment by nmvalera** [comment] 2021-01-04 21:14
@carlosho17 Referring to @SatpalSandhu61 comment above https://github.com/ConsenSys/quorum/issues/1108#issuecomment-754052677

1. You were doing the right thing by resetting the geth directory. 
2. Once reset could you please make sure that you are properly running the `geth init` command with right path to your `genesis.json` file, something like: `geth --datadir /root/alastria/data init <path-to-genesis>`
3. Then start the node

Thanks

**Comment by SatpalSandhu61** [comment] 2021-01-05 11:20
It looks like the `static-node.json` is not set up correctly.
Check that it contains the correct details for each node, that it's in the correct data dir and has the correct read permissions.

**Comment by carlosho17** [comment] 2021-01-05 17:41
Yes , it's /root/alastria/data/static-nodes.json , 0644 root root

and the contents is a normal json, with contents separated with commas
except the last one ... we pull the static-nodes.json from our github
repo, if it'd be wrong there would be issues with more than 100 nodes
using the same copy

**Comment by SatpalSandhu61** [comment] 2021-01-07 11:03
Just been looking into the Alastria docs. My understanding is that the Alastria network runs a modified version of quorum geth. Presumably you are therefore connecting to nodes which are running the modified geth?
In which case it could be that you are seeing compatibility issues with the modified geth.

**Comment by carlosho17** [comment] 2021-01-07 11:13
Hi Satpal,

indeed this is a bootnode that connects to geth 1.8 and geth 1.9 clients
(there are in fact many regular nodes on 20.10)  .. there had been
modifications in 1.8 concerning websockets information only, but no
modifications at protocol level or such.

IMHO the panic code needs to be reviewed (what triggers the panic
exactly), I can do that if you guys don't but I would end up submitting
a PR when 1.9.7 is already behind the newest version, which is non-sense.

So far I've tried a plethora of versions including the pre-packaged
ones, and the results are always the same: panic on existing chaindata,
and no sync with fresh initialized geth directory

Regards

Carlos

**Comment by SatpalSandhu61** [comment] 2021-01-07 12:14
The panic occurs on the following line in the block downloader during a sync:
```
header := d.lightchain.GetHeaderByHash(h) // Independent of sync mode, header surely exists
```
We believe the cause of the panic is a db corruption, which could happen if the node was hard-killed or crashed for some reason. This is a known issue in upstream geth (see https://github.com/ethereum/go-ethereum/issues/21421)

Therefore the correct thing to do is to re-init the node as per my earlier suggestion. The issues you are seeing after performing the re-init appear to be a failure to successfully connect to other nodes. That warrants investigation and is most likely due to misconfiguration or incompatibility with the modified code on the other nodes.

**Comment by antonydenyer** [comment] 2022-04-04 11:18
I'm assuming this has been fixed now, feel free to re-open if that is not the case

**Closed as completed by antonydenyer** 2022-04-04 11:18 UTC
