### ISSUE TITLE
Prevent DDoS Attack in Quorum

### ISSUE THREAD

**Issue by jiten-balla** [Consensys-Incorporated/quorum#793] opened 2019-08-05 10:34 UTC
Hi there,

My team wants to implement private chain using Quorum, We feel Quorum is a very good project and my team has very good confidence in this project.

In Ethereum DDoS attacks are gas-consuming because the attacker needs to spend real money. In the case of Quorum gasPrice is zero, can you please suggest us how to prevent DDoS attack for Quorum. 

We tested our network with 20,000 tx's executing same time, but we got a couple of issues.
* Someone else mined invalid block ignoring block
* We try to execute same with ~800 tx's, all transactions are in the same block, Is there any way to add transactions in a max block sizes, so that nodes will add into the pool. It's easy to 
* Invalid JSON RPC response: ""
 
#### System information

Geth version: `geth 1.8.18-stable-b0e3c851`

OS & Version: Windows/Linux/OSX

#### Logs:
raft2019/07/30 15:36:28 INFO: 1 is starting a new election at term 52
raft2019/07/30 15:36:28 INFO: 1 became candidate at term 53
raft2019/07/30 15:36:28 INFO: 1 received MsgVoteResp from 1 at term 53
raft2019/07/30 15:36:28 INFO: 1 [logterm: 46, index: 298] sent MsgVote request to 2 at term 53
raft2019/07/30 15:36:28 INFO: 1 [logterm: 46, index: 298] sent MsgVote request to 3 at term 53
raft2019/07/30 15:36:28 INFO: 1 received MsgVoteResp rejection from 2 at term 53
raft2019/07/30 15:36:28 INFO: 1 [quorum:2] has received 1 MsgVoteResp votes and 1 vote rejections
raft2019/07/30 15:36:29 INFO: 1 [term: 53] received a MsgVote message with higher term from 2 [term: 54]
raft2019/07/30 15:36:29 INFO: 1 became follower at term 54
raft2019/07/30 15:36:29 INFO: 1 [logterm: 46, index: 298, vote: 0] cast MsgVote for 2 [logterm: 51, index: 306] at term 54
raft2019/07/30 15:36:29 INFO: raft.node: 1 elected leader 2 at term 54
INFO [07-30|15:36:29.721] QUORUM-CHECKPOINT                        name=BECAME-VERIFIER
INFO [07-30|15:36:29.751] persisted the latest applied index       index=299
INFO [07-30|15:36:29.807] Non-extending block                      block=b724eb…8dbbbc                                                    parent=68ab3b…b0caad head=d67df6…40455b
INFO [07-30|15:36:29.807] persisted the latest applied index       index=300
INFO [07-30|15:36:29.807] Handling InvalidRaftOrdering             invalid block=b724eb…8dbbbc current head=d67df6…40455b
INFO [07-30|15:36:29.807] Someone else mined invalid block; ignoring block=b724eb…8dbbbc
INFO [07-30|15:36:29.869] Non-extending block                      block=9dc26b…ef6514                                                    parent=b724eb…8dbbbc head=d67df6…40455b

**Comment by jbhurat** [comment] 2019-08-05 21:05
>* Someone else mined invalid block ignoring block
>* We try to execute same with ~800 tx's, all transactions are in the same block, Is there any way to add transactions in a max block sizes, so that nodes will add into the pool. It's easy to 
>* Invalid JSON RPC response: ""

Hi @jiten-balla, regarding the queries you had. 
* `Someone else mined invalid block ignoring block` this usually happens in raft when a leader election happened, may be due to leader being restarted, and the old leader still mined the block. Was this the case
* `We try to execute same with ~800 tx's, all transactions are in the same block, Is there any way to add transactions in a max block sizes, so that nodes will add into the pool. It's easy to ` The number of transactions in the block are limited by block gas limit, looks like in your case the gas used by all the ~800 txn's were within the gas limit
* `Invalid JSON RPC response: ""` Can you provide more details around what were you trying to do here

**Comment by jiten-balla** [comment] 2019-08-07 04:30
Thanks for quick response and  @jbhurat.  Please find my inline comments for the same.

> Someone else mined invalid block ignoring block this usually happens in raft when a leader election happened, maybe due to the leader being restarted, and the old leader still mined the block. Was this the case

We know this is the issue, can you please explain how to fix this issue.

> We try to execute same with ~800 tx's, all transactions are in the same block, Is there any way to add transactions in a max block sizes, so that nodes will add into the pool. It's easy to The number of transactions in the block are limited by block gas limit, looks like in your case the gas used by all the ~800 txn's were within the gas limit

Thanks, We have done modifications in the genesis block, Sorry I forgot.

> Invalid JSON RPC response: "" Can you provide more details around what were you trying to do here

During election change when we are trying to get transaction details, I am getting above error.


**Can you please explain how to prevent DDoS attack in Quorum. Currently, this is our P0 item.**

**Comment by jbhurat** [comment] 2019-08-07 15:27
* Regarding preventing DDoS attack in Quorum - In Quorum, the concept of gas is still there, but the gas price is zero, which means that the transactions are still bound by the gas limit configured in genesis or passed as arguments to `geth` and the transactions which use gas above this limit will be rejected (same behavior as `Ethereum`). Also checkout [Security Framework](https://docs.goquorum.com/en/latest/Security/Framework/Overview/) for the best practices around how to secure Quorum Network and Dapps 

* `Someone else mined invalid block ignoring block` This is not an error, but an info message that the block was mined by a node which is no longer minter and the block is being ignored, the transactions included in the block will be returned to the transaction pool and will be included in the subsequent blocks.

* `Invalid JSON RPC response: ""` - I haven't been able to reproduce this. Can you provide a reproducible example

**Comment by fixanoid** [comment] 2019-08-14 14:37
@jiten-balla please reopen if further information is required. Thanks.

**Closed as completed by fixanoid** 2019-08-14 14:37 UTC

**Comment by param-net** [comment] 2019-08-20 05:03
Thanks for reply. I was wondering how gas will workout for private transactions?. Where is the gas will be detected in msg.sender / tx initiator account. I do understand for public transactions, how private transactions gas will be calculated what will be fault tolerance for the leader in terms of gas calculation.

**Comment by jiten-balla** [comment] 2019-08-20 05:15
@fixanoid and @jbhurat Thanks for your reply. I was wondering how gas will calculate for private transactions?. As far as I know, Quorum is not supporting transferring ethers via a private transaction, in that case, how the leader will calculate gas for private transactions, what will be fault tolerance for the leader in terms of gas calculation. For public transactions, gas calculation is very straight forward.
