### ISSUE TITLE
Repeated TX processing leads to "nonce too low" error

### ISSUE THREAD

**Issue by k1rill-fedoseev** [Consensys-Incorporated/quorum#1008] opened 2020-06-02 09:05 UTC
#### System information

Geth version: quorum docker image `quorumengineering/quorum:latest`

OS & Version: Docker Desktop for Mac

Used docker image digest: `12691dd69ce137b74afec93850e143ab4a3e573fef9140e3f5fabe070e18210e`

#### Expected behaviour

Every incoming transaction should be processed only once.

#### Actual behaviour

I can see the following behaviour on Geth logs: https://gist.github.com/k1rill-fedoseev/648582b9aef497851363bb876201cb4e

Seems that quorum receiver a valid transaction, included it into a new block. Mined transaction should be removed from txpool. However, Geth tries to process it once again and fails since the account nonce was already incremented.

This does not happen all the time, some transactions are handled correctly.

#### Steps to reproduce the behaviour

Try to run the following shell script, https://gist.github.com/k1rill-fedoseev/9386aa5b6a5f751eb7c0a1e3126d43b7

**Comment by SatpalSandhu61** [comment] 2020-06-02 09:38
I've observed this issue recently. The "nonce too low" message occurs spuriously,  however I believe the transactions are processed correctly.
We are looking into this issue.

**Comment by vsmk98** [comment] 2020-07-09 13:22
Hi @k1rill-fedoseev, I am able reproduce the issue. Even in case where the error is coming, the actual transaction processing happens only once. The issue is happening because of the high throughput design of Raft. I am looking at how we can improve the transaction processing to avoid this error and improve overall messaging in the logs. I will revert back.

**Comment by vsmk98** [comment] 2020-10-09 01:51
The issue is because of a race condition between transaction processing at `txPool` and Raft consensus minting the block where in the minting process picks up the transaction which has been already processed in the previous block but not yet removed from `txPool` resulting in the error. 

This has been addressed in upstream geth version `1.9.11`. Will be fixed as a part of next `geth` upgrade of Quorum

**Closed as completed** 2021-11-16 14:50 UTC
Labels: bug, geth upstream upgrade

**Comment by baptiste-b-pegasys** [comment] 2021-11-16 14:52
Checkout GoQuorum v2021.10.1 with go-ethereum v1.9.25 for fix.
