### ISSUE TITLE
Fatal: failed to find local enode ID "" amongs peer IDs: []

### ISSUE THREAD

**Issue by princesinha19** [Consensys-Incorporated/quorum#561] opened 2018-10-28 04:41 UTC
Geth & Quorum version : 
```
Geth
Version: 1.7.2-stable
Git Commit: 0d0c507a5945ab63c8441007f022a143e2418f1e
Quorum Version: 2.1.1
Architecture: amd64
Network Id: 1337
Go Version: go1.11.1
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
```

I am trying to run Quorum on local node without vagrant or 7nodes example. 
I run the command:-
`geth --permissioned --rpc --raft --raftport "30300" --rpccorsdomain console`

I have already set up a static-nodes.json file inside a .ethereum directory. It consists of a single peer.  But when I run above command then it gives an error:-

**Fatal: failed to find local enode ID** (my_enode_id) **amongst peer IDs :** [peer_node_enode_id]

Can anyone help me with this error?

**Comment by vsmk98** [comment] 2018-10-31 08:41
This looks like a mismatch at static-nodes.json level. Can you please check of the raftport is matching between the geth command and inside static-nodes.json? can you share the start script (init and start scripts) and static-nodes.json?

**Comment by princesinha19** [comment] 2018-10-31 10:04
@vsmk98 
I am using the command:-
`geth --permissioned --rpc --raft --raftport "50401" --rpccorsdomain console`

and static-nodes.json file is:-
![static-nodes](https://user-images.githubusercontent.com/28489437/47780872-546f3180-dd22-11e8-8db5-00ac8ba80c54.png)

I am not usig any script.

**Comment by fixanoid** [comment] 2018-11-05 17:04
@princesinha19 were you able to resolve this issue?

**Comment by princesinha19** [comment] 2018-11-06 03:31
@fixanoid No. 
This issue still exists.

**Comment by thpun** [comment] 2018-11-06 06:48
what about the _permissioned-nodes.json_ file?

**Comment by princesinha19** [comment] 2018-11-06 18:33
@thpun can you please elaborate your point.
`what about the permissioned-nodes.json file?
`

Yes, I have created permissioned-nodes.json file. I think the above problem is of raft consensus.

**Comment by fixanoid** [comment] 2018-11-09 16:49
@princesinha19 please see https://github.com/jpmorganchase/quorum-examples/tree/master/examples/7nodes#permissions and also note that both static-nodes and permissioned-nodes files are required see init: https://github.com/jpmorganchase/quorum-examples/blob/master/examples/7nodes/raft-init.sh#L12

**Comment by princesinha19** [comment] 2018-11-10 04:19
@fixanoid I have already created static-nodes and permissioned-nodes JSON files. Still, the problem didn't get solved.
Here is my directory structure:-
![directory structure](https://user-images.githubusercontent.com/28489437/48297442-d7844a80-e4cd-11e8-9a43-41282151e69f.png)

**Comment by SatpalSandhu61** [comment] 2018-12-27 16:10
As per the earlier responses, this is almost certainly due to an error in the static-nodes.json file.
I can reproduce this error by changing the enode value in static-nodes.json, so that it doesn't match the quorum node.
I suggest you re-generate the enode value:
```
bootnode --writeaddress --nodekey=<raft key for the node>
```
and then check that this is actually the value in the static-nodes.json (and permissioned-nodes.json).

I'll close the issue for now. Please reopen if my suggestion doesn't resolve the issue.

**Closed as completed by SatpalSandhu61** 2018-12-27 16:10 UTC
