### ISSUE TITLE
Rebase from Geth 1.6

### ISSUE THREAD

**Issue by stevenroose** [Consensys-Incorporated/quorum#100] opened 2017-04-19 11:11 UTC
Now that Geth 1.6 is out, I'm wondering what the timeline is for porting Quorum to Geth 1.6.

It has an abstracted consensus layer, so it should be easier to incorporate the Quorum consensus mechanisms.

Would fix #87, #93, ...

**Comment by patrickmn** [comment] 2017-04-19 13:48
Duplicate of https://github.com/jpmorganchase/quorum/issues/93

**Closed as completed by patrickmn** 2017-04-19 13:48 UTC
Labels: duplicate, enhancement, core, upstream
