### ISSUE TITLE
Failed to start Ledger hub, disabling: libusb: not found [code -5]

### ISSUE THREAD

**Issue by Ksuleyman** [Consensys-Incorporated/quorum#94] opened 2017-04-11 21:23 UTC
#### System information

Geth version: 1.5.9
OS & Version: Windows 10
Branch, Commit Hash or Release: `git status`

#### Expected behaviour
I am trying to install mist for ether wallet and when i started the the mist.exe I got the error code below.

#### Actual behaviour
 I0411 23:36:52.448124 node/config.go:445] Failed to start Ledger hub, disabling: libusb: not found [code -5]
I0411 23:36:52.517174 cmd/utils/flags.go:613] WARNING: No etherbase set and no accounts found as default
I0411 23:36:52.517174 ethdb/database.go:83] Allotted 1024MB cache and 1024 file handles to C:\Users\Krasimir\AppData\Roaming\Ethereum\geth\chaindata
I0411 23:36:52.539330 ethdb/database.go:176] closed db:C:\Users\Krasimir\AppData\Roaming\Ethereum\geth\chaindata
I0411 23:36:52.541179 node/node.go:176] instance: Geth/v1.5.9-stable/windows/go1.7.4
I0411 23:36:52.541179 ethdb/database.go:83] Allotted 1024MB cache and 1024 file handles to C:\Users\Krasimir\AppData\Roaming\Ethereum\geth\chaindata
I0411 23:36:52.636801 eth/backend.go:187] Protocol Versions: [63 62], Network Id: 1
I0411 23:36:52.963528 eth/backend.go:205] WARNING: Wrote default ethereum genesis block
I0411 23:36:52.963528 eth/backend.go:215] Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000}
I0411 23:36:52.963528 core/blockchain.go:219] Last header: #0 [d4e56740…] TD=17179869184
I0411 23:36:52.963528 core/blockchain.go:220] Last block: #0 [d4e56740…] TD=17179869184
I0411 23:36:52.963528 core/blockchain.go:221] Fast block: #0 [d4e56740…] TD=17179869184
I0411 23:36:52.964532 p2p/server.go:340] Starting Server

#### Backtrace

````
[backtrace]
````

**Comment by patrickmn** [comment] 2017-04-11 21:31
Can you please give some more information:

- How did you build Quorum and Constellation? Did you compile from master or a release?
- Are you attaching to a geth RPCAPI on a Linux box, or trying to run Quorum on a Windows machine (we don't currently support Windows, but will in the near future)?

At first glance this seems like a mist, not quorum issue.

**Comment by patrickmn** [comment] 2017-04-11 21:32
Prior (but seemingly unrelated issue) involving the libusb error: https://github.com/jpmorganchase/quorum/issues/72

**Comment by Ksuleyman** [comment] 2017-04-11 21:40
may be i wrote the the wrong place but i seem the related codes with error: #72 and wrote it hear. I just download the mist and run it. It should be better if i  write the issue below ethereum.

**Comment by patrickmn** [comment] 2017-04-11 21:43
Ah, okay. Since this seems to be a Mist/Ethereum issue, I'll close this one.

I don't know the cause, but I'd suggest trying to rebuild the binaries to see if it solves the problem as in the other issue.

**Closed as completed by patrickmn** 2017-04-11 21:43 UTC
Labels: invalid, question, core
