### ISSUE TITLE
raft.removePeer(2) - freezes

### ISSUE THREAD

**Issue by marsrobertson** [Consensys-Incorporated/quorum#1096] opened 2020-11-12 11:56 UTC
Related: https://github.com/ConsenSys/quorum/issues/753

> However when you stop 3 nodes without the changing raft cluster, the majority of the nodes are down and the leader node will not be able to commit any transactions (including removePeer) as its not receiving majority confirmations.

Does it mean that my installation is effectively unstable, need to go nuclear?

### 1m06s: https://youtu.be/c0haAmsfExo

Short. Brief. To the point. It's only 1m06s, it illustrates the issue well.

### Log

`Served raft_removePeer`

```
raft2020/11/12 11:31:20.671663 INFO: 1 received MsgVoteResp from 1 at term 5255
raft2020/11/12 11:31:20.671672 INFO: 1 [logterm: 5, index: 13] sent MsgVote request to 2 at term 5255
DEBUG[11-12|11:31:21.891] Served raft_removePeer                   reqid=12   t=46.768µs
raft2020/11/12 11:31:21.971599 INFO: 1 is starting a new election at term 5255
raft2020/11/12 11:31:21.971644 INFO: 1 became candidate at term 5256
raft2020/11/12 11:31:21.971656 INFO: 1 received MsgVoteResp from 1 at term 5256
raft2020/11/12 11:31:21.971666 INFO: 1 [logterm: 5, index: 13] sent MsgVote request to 2 at term 5256
raft2020/11/12 11:31:23.171610 INFO: 1 is starting a new election at term 5256
raft2020/11/12 11:31:23.171654 INFO: 1 became candidate at term 5257
raft2020/11/12 11:31:23.171667 INFO: 1 received MsgVoteResp from 1 at term 5257
raft2020/11/12 11:31:23.171677 INFO: 1 [logterm: 5, index: 13] sent MsgVote request to 2 at term 5257
raft2020/11/12 11:31:24.771592 INFO: 1 is starting a new election at term 5257
raft2020/11/12 11:31:24.771636 INFO: 1 became candidate at term 5258
raft2020/11/12 11:31:24.771648 INFO: 1 received MsgVoteResp from 1 at term 5258
raft2020/11/12 11:31:24.771658 INFO: 1 [logterm: 5, index: 13] sent MsgVote request to 2 at term 5258
DEBUG[11-12|11:31:25.289] Served raft_cluster                      reqid=13   t=73.814µs
raft2020/11/12 11:31:26.371603 INFO: 1 is starting a new election at term 5258
raft2020/11/12 11:31:26.371648 INFO: 1 became candidate at term 5259
raft2020/11/12 11:31:26.371661 INFO: 1 received MsgVoteResp from 1 at term 5259
raft2020/11/12 11:31:26.371671 INFO: 1 [logterm: 5, index: 13] sent MsgVote request to 2 at term 5259
DEBUG[11-12|11:31:27.118] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
raft2020/11/12 11:31:28.071570 INFO: 1 is starting a new election at term 5259
raft2020/11/12 11:31:28.071615 INFO: 1 became candidate at term 5260
raft2020/11/12 11:31:28.071628 INFO: 1 received MsgVoteResp from 1 at term 5260
raft2020/11/12 11:31:28.071638 INFO: 1 [logterm: 5, index: 13] sent MsgVote request to 2 at term 5260
```

### System info

Ubuntu 18 LTS on AWS, everything from scratch: https://docs.goquorum.consensys.net/en/stable/Tutorials/Creating-A-Network-From-Scratch/

**Comment by marsrobertson** [comment] 2020-11-12 12:19
I have another Quorum deployment.

I do `ssh` and `geth attach` and `raft.cluster` and `raft.removePeer`

Then checking again:

```
> raft.removePeer(5)
null
> raft.cluster
```

Exactly the same list of nodes but in a slightly different order.

Maybe the minter should be on top? Maybe they should be sorted by `reaftId`? 

_(consistent ordering = easier to spot changes)_

**Comment by vsmk98** [comment] 2020-11-13 03:15
Hi @marsrobertson, I have tried to simulate the issue locally and am not able to reproduce it. These are my steps:


1. Brought up 7 nodes of Quorum ( as docker containers)
2. Killed 4 of the docker processes. My `raft.cluster` output is as below:
```
> raft.cluster
[{
    hostname: "172.16.239.12",
    nodeActive: true,
    nodeId: "0ba6b9f606a43a95edc6247cdb1c1e105145817be7bcafd6b2c0ba15d58145f0dc1a194f70ba73cd6f4cdd6864edc7687f311254c7555cc32e4d45aeb1b80416",
    p2pPort: 21000,
    raftId: 2,
    raftPort: 50400,
    role: "minter"
}, {
    hostname: "172.16.239.13",
    nodeActive: true,
    nodeId: "579f786d4e2830bbcc02815a27e8a9bacccc9605df4dc6f20bcc1a6eb391e7225fff7cb83e5b4ecd1f3a94d8b733803f2f66b7e871961e7b029e22c155c3a778",
    p2pPort: 21000,
    raftId: 3,
    raftPort: 50400,
    role: "verifier"
}, {
    hostname: "172.16.239.14",
    nodeActive: false,
    nodeId: "3d9ca5956b38557aba991e31cf510d4df641dce9cc26bfeb7de082f0c07abb6ede3a58410c8f249dabeecee4ad3979929ac4c7c496ad20b8cfdd061b7401b4f5",
    p2pPort: 21000,
    raftId: 4,
    raftPort: 50400,
    role: "verifier"
}, {
    hostname: "172.16.239.15",
    nodeActive: false,
    nodeId: "3701f007bfa4cb26512d7df18e6bbd202e8484a6e11d387af6e482b525fa25542d46ff9c99db87bd419b980c24a086117a397f6d8f88e74351b41693880ea0cb",
    p2pPort: 21000,
    raftId: 5,
    raftPort: 50400,
    role: "verifier"
}, {
    hostname: "172.16.239.16",
    nodeActive: false,
    nodeId: "eacaa74c4b0e7a9e12d2fe5fee6595eda841d6d992c35dbbcc50fcee4aa86dfbbdeff7dc7e72c2305d5a62257f82737a8cffc80474c15c611c037f52db1a3a7b",
    p2pPort: 21000,
    raftId: 6,
    raftPort: 50400,
    role: "verifier"
}, {
    hostname: "172.16.239.17",
    nodeActive: false,
    nodeId: "239c1f044a2b03b6c4713109af036b775c5418fe4ca63b04b1ce00124af00ddab7cc088fc46020cdc783b6207efe624551be4c06a994993d8d70f684688fb7cf",
    p2pPort: 21000,
    raftId: 7,
    raftPort: 50400,
    role: "verifier"
}, {
    hostname: "172.16.239.11",
    nodeActive: true,
    nodeId: "ac6b1096ca56b9f6d004b779ae3728bf83f8e22453404cc3cef16a3d9b96608bc67c4b30db88e0a5a6c6390213f7acbe1153ff6d23ce57380104288ae19373ef",
    p2pPort: 21000,
    raftId: 1,
    raftPort: 50400,
    role: "verifier"
}]
```
3. Executed `raft.removePeer` for one of the the peers and it responds back immediately:
```
> raft.removePeer(7)
null
>
```

Will it be possible for you to share the geth logs of the node from where you are executing `raft.removePeer`?

On the second issue of ordering, the output is an unordered json and suggestion will be to check the output using the raft id and not rely on the order of the output.

**Comment by marsrobertson** [comment] 2020-11-13 11:25
`ssh -i "Quorum-Testing-AWS.pem" ubuntu@ec2-3-20-233-34.us-east-2.compute.amazonaws.com` - ssh into machine

`killall geth` - kill quorum

`rm node.log` - remove the log

`./startnode1`

`geth attach new-node-1/geth.ipc`

`raft.cluster`

```
[{
    hostname: "18.216.142.10",
    nodeActive: false,
    nodeId: "e68d250d1c7aab9e3e7ac282eae5ab377a086b6714d500e6b6dcde7e1a6a630d916c81ae02772a5ae9232996ce78e3638a555674a6f32b62bda4867614ceb2a4",
    p2pPort: 21000,
    raftId: 2,
    raftPort: 50000,
    role: ""
}, {
    hostname: "3.20.233.34",
    nodeActive: true,
    nodeId: "1dc9644adf73d56f5206a7b166679d9839efa8381bafff1074159407d6c75328c619d3bcd98e3a24b29806df34e8bf44edde573bdc52125274af8d8a2a033e83",
    p2pPort: 21000,
    raftId: 1,
    raftPort: 50000,
    role: ""
}]
```

`raft.removePeer(2)`
`null`

`raft.cluster`

```
[{
    hostname: "18.216.142.10",
    nodeActive: false,
    nodeId: "e68d250d1c7aab9e3e7ac282eae5ab377a086b6714d500e6b6dcde7e1a6a630d916c81ae02772a5ae9232996ce78e3638a555674a6f32b62bda4867614ceb2a4",
    p2pPort: 21000,
    raftId: 2,
    raftPort: 50000,
    role: ""
}, {
    hostname: "3.20.233.34",
    nodeActive: true,
    nodeId: "1dc9644adf73d56f5206a7b166679d9839efa8381bafff1074159407d6c75328c619d3bcd98e3a24b29806df34e8bf44edde573bdc52125274af8d8a2a033e83",
    p2pPort: 21000,
    raftId: 1,
    raftPort: 50000,
    role: ""
}]
```

`raft.removePeer(2)`

**FREEZES**

In another terminal tab `killall geth`

```
^X^X^X^X^X^X^X^X^X^X^X^X^C^C^CError: EOF
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1
```

### Get the logs

`scp -i Quorum-Testing-AWS.pem ubuntu@ec2-3-20-233-34.us-east-2.compute.amazonaws.com:/home/ubuntu/node.log ~/node-minter.log`

[node-minter.log](https://github.com/ConsenSys/quorum/files/5536436/node-minter.log)

What makes me think - I thought this node is "minter" but the `role: ""`

----

To be honest - I'm learning here - it's just a test environment - I can just nuke everything. 

Creating this issue because I want to learn and understand - maybe I put my installation in an unstable state?

If you want to have joy debugging, fixing product, ensuring everything is stable - can totally give you access to that box.

If you are too busy - I'll just nuke everything, start fresh.

**Comment by SatpalSandhu61** [comment] 2020-11-13 15:59
In your video, before removing the node I see that you ran `raft.cluster` on node 1 and it showed node 2 with `nodeActive: false`, so I presume you are stopping node 2 and then running the `raft.removePeer(2)` command on node 1. Is that correct?

If you do that then node 2 won't actually get removed from the cluster, due to there not being sufficient live nodes to confirm the removal (as described in issue [#753](https://github.com/ConsenSys/quorum/issues/753) you mentioned earlier ). This is a quirky edge case that will occur if you only have a couple of nodes.

I went through the tutorial steps and it all worked. With node 2 running, the `raft.removePeer` worked as expected.

Having said all that, I don't understand why you saw `raft.removePeer` hanging in the way you showed on the video. I tried going through the tutorial again, but this time stopping node 2 before removing it. In this case the `raft.removePeer(2)` still returned immediately, even though it didn't remove node 2 from the cluster. In fact restarting node 2 allowed it to confirm the removal and then `raft.cluster` only showed node 1.

If you nuke the nodes and run through the tutorial once more then you should find that it works fine. If you do see that same issue with `raft.removePeer` then please let us know.

**Comment by marsrobertson** [comment] 2020-11-16 12:51
Thank you @SatpalSandhu61 for having a look.

> This is a quirky edge case that will occur if you only have a couple of nodes.

This is the most typical case when someone is learning, trying, testing, playing, messing up with stuff.

I think that adding some checks before potentially catastrophic operation is a sensible idea.

_"Removing node will... You are using Raft consensus and you need ... nodes to remain online."_


### It was working briefly for a single moment

Monday arrived to work, checked the current status. Magic

![2020-11-16 Quorum cluster coming online](https://user-images.githubusercontent.com/44369284/99249671-61c0c100-2802-11eb-80c2-1fad5540381a.png)

### Now it is in some strange unstable state again

Node 2 (verifier): `killall geth`

Node 1 (minter): `raft.removePeer(2)`

### Cannot get it back online?

Node 2:
- `rm node.log`
- `./startnode2`

```
DEBUG[11-16|12:41:19.011] Sanitizing Go's GC trigger               percent=100
INFO [11-16|12:41:19.013] Maximum peer count                       ETH=50 LES=0 total=50
INFO [11-16|12:41:19.013] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
DEBUG[11-16|12:41:19.013] FS scan times                            list=32.474µs set=2.122µs diff=2.563µs
TRACE[11-16|12:41:19.013] Started watching keystore folder         path=/home/ubuntu/new-node-2/keystore
ERROR[11-16|12:41:19.013] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[11-16|12:41:19.013] Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[11-16|12:41:19.014] Failed to enumerate USB devices          hub=trezor vendor=4617  failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[11-16|12:41:19.014] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[11-16|12:41:19.014] Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[11-16|12:41:19.014] Failed to enumerate USB devices          hub=trezor vendor=4617  failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
WARN [11-16|12:41:19.014] Using deprecated resource file /home/ubuntu/new-node-2/nodekey, please move this file to the 'geth' subdirectory of datadir. 
WARN [11-16|12:41:19.014] Found deprecated node list file /home/ubuntu/new-node-2/static-nodes.json, please use the TOML config file instead. 
INFO [11-16|12:41:19.014] Starting peer-to-peer node               instance=Geth/v1.9.7-stable-1ecd4262(quorum-v20.10.0)/linux-amd64/go1.15.3
INFO [11-16|12:41:19.014] Allocated trie memory caches             clean=256.00MiB dirty=256.00MiB
INFO [11-16|12:41:19.014] Allocated cache and file handles         database=/home/ubuntu/new-node-2/geth/chaindata cache=768.00MiB handles=524288
DEBUG[11-16|12:41:19.032] Chain freezer table opened               database=/home/ubuntu/new-node-2/geth/chaindata/ancient table=headers items=0 size=0.00B
DEBUG[11-16|12:41:19.032] Chain freezer table opened               database=/home/ubuntu/new-node-2/geth/chaindata/ancient table=hashes  items=0 size=0.00B
DEBUG[11-16|12:41:19.032] Chain freezer table opened               database=/home/ubuntu/new-node-2/geth/chaindata/ancient table=bodies  items=0 size=0.00B
DEBUG[11-16|12:41:19.032] Chain freezer table opened               database=/home/ubuntu/new-node-2/geth/chaindata/ancient table=receipts items=0 size=0.00B
DEBUG[11-16|12:41:19.032] Chain freezer table opened               database=/home/ubuntu/new-node-2/geth/chaindata/ancient table=diffs    items=0 size=0.00B
INFO [11-16|12:41:19.032] Opened ancient database                  database=/home/ubuntu/new-node-2/geth/chaindata/ancient
DEBUG[11-16|12:41:19.032] Privacy metadata root                    hash=000000…000000
INFO [11-16|12:41:19.032] Initialised chain configuration          config="{ChainID: 10 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 IsQuorum: true Constantinople: 0 TransactionSizeLimit: 64 MaxCodeSize: 0 Petersburg: <nil> Istanbul: <nil> PrivacyEnhancements: <nil> Engine: unknown}"
WARN [11-16|12:41:19.032] Ethash used in full fake mode 
INFO [11-16|12:41:19.032] Initialising Ethereum protocol           name=eth versions="[64 63]" network=31337 dbversion=7
DEBUG[11-16|12:41:19.036] Current full block not old enough        number=0 hash=375fbb…d806d0 delay=3162240
DEBUG[11-16|12:41:19.090] Privacy metadata root                    hash=000000…000000
DEBUG[11-16|12:41:19.090] Privacy metadata root                    hash=000000…000000
INFO [11-16|12:41:19.090] Loaded most recent local header          number=0 hash=375fbb…d806d0 td=0 age=51y7mo1w
INFO [11-16|12:41:19.090] Loaded most recent local full block      number=0 hash=375fbb…d806d0 td=0 age=51y7mo1w
INFO [11-16|12:41:19.090] Loaded most recent local fast block      number=0 hash=375fbb…d806d0 td=0 age=51y7mo1w
DEBUG[11-16|12:41:19.090] Privacy metadata root                    hash=000000…000000
DEBUG[11-16|12:41:19.090] Privacy metadata root                    hash=000000…000000
DEBUG[11-16|12:41:19.090] Reinjecting stale transactions           count=0
INFO [11-16|12:41:19.090] Loaded local transaction journal         transactions=0 dropped=0
INFO [11-16|12:41:19.090] Regenerated local transaction journal    transactions=0 accounts=0
INFO [11-16|12:41:19.102] Allocated fast sync bloom                size=512.00MiB
WARN [11-16|12:41:19.103] Using deprecated resource file new-node-2/nodekey, please move this file to the 'geth' subdirectory of datadir. 
WARN [11-16|12:41:19.103] Found deprecated node list file new-node-2/static-nodes.json, please use the TOML config file instead. 
INFO [11-16|12:41:19.108] Initialized fast sync bloom              items=1 errorrate=0.000 elapsed=1.944ms
DEBUG[11-16|12:41:19.108] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
INFO [11-16|12:41:19.124] starting raft protocol handler 
INFO [11-16|12:41:19.124] loaded the latest applied index          lastAppliedIndex=0
INFO [11-16|12:41:19.124] loading snapshot 
INFO [11-16|12:41:19.124] applying snapshot to raft storage 
INFO [11-16|12:41:19.125] updating cluster membership per raft snapshot 
INFO [11-16|12:41:19.125] adding new raft peer                     raft id=1
DEBUG[11-16|12:41:19.125] TCP listener up                          addr=[::]:21000
INFO [11-16|12:41:19.126] New local node record                    seq=4 id=e4445634238b5b07 ip=127.0.0.1 udp=0 tcp=21000
INFO [11-16|12:41:19.126] Started P2P networking                   self="enode://867f26c7014c19ae96a11d6536834dbe876a73c6a71856d5a94bb483153f2c5312e6f6f24a6fbbbb1bdd5310500add1a4b6d2eb77669eba011dd1ec880c696df@127.0.0.1:21000?discport=0"
WARN [11-16|12:41:19.126] Removing static dial candidate           id=0x9ef940         addr=18.216.142.10:21001 err="is self"
TRACE[11-16|12:41:19.126] New dial task                            task="staticdial 6bb816cc897403a0 3.20.233.34:21000"
TRACE[11-16|12:41:19.126] Adding static node                       node="enode://1dc9644adf73d56f5206a7b166679d9839efa8381bafff1074159407d6c75328c619d3bcd98e3a24b29806df34e8bf44edde573bdc52125274af8d8a2a033e83@3.20.233.34:21000?discport=0&raftport=50000"
TRACE[11-16|12:41:19.127] Failed RLPx handshake                    addr=3.20.233.34:21000   conn=staticdial err=EOF
TRACE[11-16|12:41:19.127] Setting up connection failed             addr=3.20.233.34:21000   err=EOF
TRACE[11-16|12:41:19.127] Dial error                               task="staticdial 6bb816cc897403a0 3.20.233.34:21000" err=EOF
TRACE[11-16|12:41:19.127] Dial task done                           task="staticdial 6bb816cc897403a0 3.20.233.34:21000"
TRACE[11-16|12:41:19.127] New dial task                            task="wait for dial hist expire (34.999995843s)"
INFO [11-16|12:41:19.130] updated cluster membership 
INFO [11-16|12:41:19.130] synchronizing with peer                  peer id=1 hash=023a99…44f3bb
INFO [11-16|12:41:19.130] Block synchronisation started 
DEBUG[11-16|12:41:19.130] Reset ancient limit to zero 
WARN [11-16|12:41:19.130] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [11-16|12:41:19.130] failed to synchronize with peer          peer id=6bb816cc897403a00f1be8f6ca717c256f5b88f54c36c8c1e073637d8afbf639
INFO [11-16|12:41:19.630] synchronizing with peer                  peer id=1 hash=023a99…44f3bb
DEBUG[11-16|12:41:19.630] Reset ancient limit to zero 
WARN [11-16|12:41:19.630] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [11-16|12:41:19.630] failed to synchronize with peer          peer id=6bb816cc897403a00f1be8f6ca717c256f5b88f54c36c8c1e073637d8afbf639
ERROR[11-16|12:41:20.020] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=3 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[11-16|12:41:20.020] Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=3 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[11-16|12:41:20.020] Failed to enumerate USB devices          hub=trezor vendor=4617  failcount=3 err="failed to initialize libusb: libusb: unknown error [code -99]"
INFO [11-16|12:41:20.131] synchronizing with peer                  peer id=1 hash=023a99…44f3bb
DEBUG[11-16|12:41:20.131] Reset ancient limit to zero 
WARN [11-16|12:41:20.131] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [11-16|12:41:20.131] failed to synchronize with peer          peer id=6bb816cc897403a00f1be8f6ca717c256f5b88f54c36c8c1e073637d8afbf639
INFO [11-16|12:41:20.631] synchronizing with peer                  peer id=1 hash=023a99…44f3bb
DEBUG[11-16|12:41:20.631] Reset ancient limit to zero 
WARN [11-16|12:41:20.631] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [11-16|12:41:20.631] failed to synchronize with peer          peer id=6bb816cc897403a00f1be8f6ca717c256f5b88f54c36c8c1e073637d8afbf639
INFO [11-16|12:41:21.131] synchronizing with peer                  peer id=1 hash=023a99…44f3bb
DEBUG[11-16|12:41:21.131] Reset ancient limit to zero 
WARN [11-16|12:41:21.131] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [11-16|12:41:21.132] failed to synchronize with peer          peer id=6bb816cc897403a00f1be8f6ca717c256f5b88f54c36c8c1e073637d8afbf639
DEBUG[11-16|12:41:21.225] Couldn't add port mapping                proto=tcp extport=21000 intport=21000 interface="UPnP or NAT-PMP" err="no UPnP or NAT-PMP router discovered"
INFO [11-16|12:41:21.632] synchronizing with peer                  peer id=1 hash=023a99…44f3bb
DEBUG[11-16|12:41:21.632] Reset ancient limit to zero 
WARN [11-16|12:41:21.632] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [11-16|12:41:21.632] failed to synchronize with peer          peer id=6bb816cc897403a00f1be8f6ca717c256f5b88f54c36c8c1e073637d8afbf639
INFO [11-16|12:41:22.132] synchronizing with peer                  peer id=1 hash=023a99…44f3bb
DEBUG[11-16|12:41:22.132] Reset ancient limit to zero 
WARN [11-16|12:41:22.132] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [11-16|12:41:22.132] failed to synchronize with peer          peer id=6bb816cc897403a00f1be8f6ca717c256f5b88f54c36c8c1e073637d8afbf639
INFO [11-16|12:41:22.632] synchronizing with peer                  peer id=1 hash=023a99…44f3bb
```

-----

I'm really confused by the fact it was working temporarily (screenshots attached) - it would be easier if it was not working consistently 😇

PS. It's not important really. Just me learning. Can send private key via private message if anyone wants to entertain their intellectual curiosity - solving bugs for fun and profit. Better more stable products = more clients and more money coming to the business.

**Comment by vsmk98** [comment] 2020-11-17 12:45
HI @marsrobertson, Thanks for sharing all the details. We are able to reproduce this issue. The issue happens when you try `raft.removePeer` second time on a network which does not have a Raft Quorum. Will raise a PR to fix this.

**Comment by melihbirim** [comment] 2020-11-19 10:03
Here is a similar scenario on my side.

1 - Create a network with 6 nodes (nodes listed in static.json)
2- Start with only 2 nodes, let's say nodes 5 and 6 is running
3- Attach console of the 5th node and try to remove any not working one (raft.removePeer(1))
4- first it prints 'null' on the second try it hangs.

**Comment by SatpalSandhu61** [comment] 2020-11-23 14:27
Closing this ticket. The issue is fully explained with details in #1099

**Closed as completed by SatpalSandhu61** 2020-11-23 14:27 UTC
