### ISSUE TITLE
Memory issue when using Raft  

### ISSUE THREAD

**Issue by WesleyLiu0717** [Consensys-Incorporated/quorum#913] opened 2019-12-16 06:46 UTC
Hi there,
we are doing some tests for quorum with its built-in raft consensus. However, as we sent 300 transactions/second to 4 nodes which are executed on 4 different computers in round-robin for 30 minutes, the memory usage on each node would be “monotonically increasing”. And most importantly, it seems that no block would be mined after reaching some particular memory usage, and all the remaining transactions would be queued or pending in each node’s txpool.
In addition, we also finished some tests to confirm our experiment setting is valid:
1. send 100 transactions/second in round-robin for a period of 10 minutes, the total transactions would be written in the blocks
2. send 100 transactions/second in round-robin for three days, the nodes cannot reach consensus after nodes reach about 40% memory usage (16 * 40 % = 6.4 G)
We wonder whether someone gets the same issue, or how to resolve it.
Many thanks!

Note:
All transactions are used for executing functions in smart contract. The gas used is about 246069, 157158 (two different functions).
The instruction of node execution is
geth --miner.gastarget 700000000 --miner.gaslimit 700000000 --nodiscover --verbosity 5 --networkid 10 --raft --raftport 50400 --rpc --rpcaddr 0.0.0.0 --emitcheckpoints --port 30303 --ws --wsorigins "*" --wsaddr 0.0.0.0 console

The following image shows the cpu and memory usage of 300 transactions/second for 30 minutes. The computer of 16-core cpu and 14.4G memory is used in this test.
![The cpu and memory usage with 300 input rates for 30 minutes](https://user-images.githubusercontent.com/46731787/70884152-0d202f00-2010-11ea-9863-f81abcb41a3a.png)

#### System information
Quorum version: v2.4.0
OS & Version: Ubuntu 18.04

#### Expected behaviour
After transactions are confirmed (written in blocks), the memory on each nodes should be released.

#### Actual behaviour
After transactions are confirmed, the memory on each node does not be released, and as it reach a particular usage, the nodes cannot work properly.

#### Steps to reproduce the behaviour
Use web3 websocket provider to send 300 transactions/second to 4 nodes for more than 1 hour.

**Comment by trung** [comment] 2019-12-16 20:14
@WesleyLiu0717 thanks for providing the details. I would like to know more about your setup so i can give a try to replicate the issue you are seeing.

1. What kind of transactions do you submit to the network? (public vs private)
1. What ports are exposed to the internet? (HTTP,  WS, Raft, P2P, Tessera P2P, Tessera Third Party)
1. Is there any supporting tools running in the setup? proxies, nginx, log shippers ...
1. I understand that you are using websocket in the test. Would you be able to replicate the issue with HTTP endpoint?
1. Would you be able to share your smart contract being used in the test?

**Comment by WesleyLiu0717** [comment] 2019-12-17 07:13
Hi @trung, 
1. We use web3.eth.accounts.signTransaction to sign transaction and web3.eth.sendSignedTransaction to send transaction. The web3.eth.getTransaction shows "v" is "0x38"(0x38 = 56 = 10*2+36), which means the transaction is public. 
2. The enode in static-nodes.json is like "enode://92fdd4da34561c313a006deac1565307207338a375b2d524a28260ea5a006b61fe828df9dce88e7797bc99bff8db5707bea4d597b0ed75a99ec31349010d803a@some-ip:30303?discport=0&raftport=50400". HTTP, WS, Raft and P2P are exposed to the internet (internal network). 
3. There is no supporting tool running in this experiment.
4. We also try the http provider, but it can't send transaction for a long period of time (Such as 200 transactions/second for 10 minutes).  
5. The origin smart contract is complicated, so I simplify it. The same issue occurs in the same experiment. 

Note: The same issue occurs in IBFT after sending 100 transactions/second for 15 hours.

### Smart contract 
```solidity
pragma solidity ^0.4.25;

contract TestContract {

    struct Log {
        string id;
        string message;
        uint timestamp;
        uint status;
    }

    uint logLength = 0;
    mapping(uint => Log) logList;

    function log(string id, string message, uint timestamp, uint status) external {
        logList[logLength] = Log(id, message, timestamp, status);
        logLength++;
    }

    function retrieveLogLength() external view returns (uint) {
        return logLength;
    }
}
```
#### Bytecode
`60806040526000805534801561001457600080fd5b506102c1806100246000396000f30060806040526004361061004c576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680633fe2156214610051578063f45d7d2c1461007c575b600080fd5b34801561005d57600080fd5b506100666100e3565b6040518082815260200191505060405180910390f35b34801561008857600080fd5b506100e160048036038101908080359060200190820180359060200191909192939192939080359060200190820180359060200191909192939192939080359060200190929190803590602001909291905050506100ec565b005b60008054905090565b60806040519081016040528087878080601f016020809104026020016040519081016040528093929190818152602001838380828437820191505050505050815260200185858080601f016020809104026020016040519081016040528093929190818152602001838380828437820191505050505050815260200183815260200182815250600160008054815260200190815260200160002060008201518160000190805190602001906101a29291906101f0565b5060208201518160010190805190602001906101bf9291906101f0565b5060408201518160020155606082015181600301559050506000808154809291906001019190505550505050505050565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061023157805160ff191683800117855561025f565b8280016001018555821561025f579182015b8281111561025e578251825591602001919060010190610243565b5b50905061026c9190610270565b5090565b61029291905b8082111561028e576000816000905550600101610276565b5090565b905600a165627a7a72305820da7bb39e93392076aeef736c44fceb45e003e709f55f3beb49a85ff073b9fc850029`

#### ABI
```json
[
	{
		"constant": true,
		"inputs": [],
		"name": "retrieveLogLength",
		"outputs": [
			{
				"name": "",
				"type": "uint256"
			}
		],
		"payable": false,
		"stateMutability": "view",
		"type": "function"
	},
	{
		"constant": false,
		"inputs": [
			{
				"name": "id",
				"type": "string"
			},
			{
				"name": "message",
				"type": "string"
			},
			{
				"name": "timestamp",
				"type": "uint256"
			},
			{
				"name": "status",
				"type": "uint256"
			}
		],
		"name": "log",
		"outputs": [],
		"payable": false,
		"stateMutability": "nonpayable",
		"type": "function"
	}
]
```

**Comment by trung** [comment] 2019-12-17 15:19
@WesleyLiu0717 thanks for getting back. 

My initial observation is that the smart contract being used maintains an **always-growing** data structure `logList`.  With the duration and intensive TPS of your experiment, `logList` requires more storage and this would result a gradual increase in 

* Gas being used for transactions
* Node's memory usage

Both of the above could potentially create a substantial effect on the node. 

To rule out the above, my suggestion is to use a `SimpleStorage` smart contract. That way if the issue happened again, we would look into potential memory leak . If it didn't happen, we would be in a better position to focus on the root cause.

[Here is the reference](https://github.com/jpmorganchase/quorum-acceptance-tests/blob/master/src/main/sol/SimpleStorage.sol) to the `SimpleStorage` smart contract

**Comment by fixanoid** [comment] 2019-12-17 15:28
One way to address logging would be to emit these as events and collect them outside of the smart contract. There are many articles on the topic, here is one that should [help](https://media.consensys.net/technical-introduction-to-events-and-logs-in-ethereum-a074d65dd61e).

**Comment by WesleyLiu0717** [comment] 2019-12-17 16:21
Hi @trung @fixanoid,
Thanks for your suggestion,
I'll try to replace the current smart contract with SimpleStorage version.
If the same problem occurs, I'll update here.

**Comment by fixanoid** [comment] 2019-12-17 16:30
Please reopen once done. Thanks!

**Comment by WesleyLiu0717** [comment] 2019-12-18 09:23
Hi @trung,
I've try the SimpleStorage version and the same problem also occurs.
We sent 100 transactions/second to 4 nodes in round-robin and go-ethereum/ethereum V1.8.18-stable POA is used to be a control group.
The memory of Raft is still “monotonically increasing” and cannot get the consensus after a while, but POA releases some memory at intervals and successfully run the experiment last for 2 hours.

Is there any ideal about it?
Many thanks! 

### Smart contract
```solidity
pragma solidity ^0.4.25;
contract TestContract {

    uint logLength = 0;
    bytes32 SN;
    bytes32 dataHash;
    uint timestamp;
    uint status;

    function log(bytes32 _SN, bytes32 _dataHash, uint _timestamp, uint _status) external {
        SN = _SN;
        dataHash = _dataHash;
        timestamp = _timestamp;
        status = _status;
        logLength++;
    }

    function retrieveLogLength() external view returns (uint) {
        return logLength;
    }

}
```
Bytecode
```
60806040526000805534801561001457600080fd5b5061013f806100246000396000f30060806040526004361061004c576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680632736fe30146100515780633fe21562146100a4575b600080fd5b34801561005d57600080fd5b506100a26004803603810190808035600019169060200190929190803560001916906020019092919080359060200190929190803590602001909291905050506100cf565b005b3480156100b057600080fd5b506100b961010a565b6040518082815260200191505060405180910390f35b836001816000191690555082600281600019169055508160038190555080600481905550600080815480929190600101919050555050505050565b600080549050905600a165627a7a72305820b3f023e57091bef5973fd747348aaf4c4ac8ee85b5a4de22d08db84554087a9c0029
```
ABI
```
[
	{
		"constant": false,
		"inputs": [
			{
				"name": "_SN",
				"type": "bytes32"
			},
			{
				"name": "_dataHash",
				"type": "bytes32"
			},
			{
				"name": "_timestamp",
				"type": "uint256"
			},
			{
				"name": "_status",
				"type": "uint256"
			}
		],
		"name": "log",
		"outputs": [],
		"payable": false,
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"constant": true,
		"inputs": [],
		"name": "retrieveLogLength",
		"outputs": [
			{
				"name": "",
				"type": "uint256"
			}
		],
		"payable": false,
		"stateMutability": "view",
		"type": "function"
	}
]
```

**Comment by trung** [comment] 2019-12-18 16:08
@WesleyLiu0717 thanks for sharing the experiment outcome. 

Can you share the logs from all the nodes in the network?

**Comment by WesleyLiu0717** [comment] 2019-12-19 10:21
Hi @trung,

We sent 200 tx/s for 3 hours and logged all the data.
The experiment is from 11:03.
Since the log file is too big and there are some private information concerned, I follow some keyword to get the information.
If there is another keyword you are curious about, please tell me.

1. Imported: which is used to trace the block insertion
Under the observation of node 4, we think there is something wrong at 13:41:XX
4 node have different block number, node1: 54914 node2 and 3: 54904, node4: 54817.
node1:
![imported_node1](https://user-images.githubusercontent.com/46731787/71165000-03eec680-228b-11ea-9d99-b299f7eefbcc.png)
![imported_finally_node1](https://user-images.githubusercontent.com/46731787/71165052-1ec13b00-228b-11ea-94f4-85d8aa181018.png)
node2:
![imported_node2](https://user-images.githubusercontent.com/46731787/71165100-3993af80-228b-11ea-9599-ae4a4b856cf0.png)
![imported_finally_node2](https://user-images.githubusercontent.com/46731787/71165114-3e586380-228b-11ea-8939-939b0dcb33ff.png)
node3:
![imported_node3](https://user-images.githubusercontent.com/46731787/71165138-4ca67f80-228b-11ea-87e9-3c7fffbd4115.png)
![imported_finally_node3](https://user-images.githubusercontent.com/46731787/71165147-4fa17000-228b-11ea-996b-b88629be0829.png)
node4:
![imported_finally_node4](https://user-images.githubusercontent.com/46731787/71165158-57f9ab00-228b-11ea-8791-790cf25012d0.png)

2. Transaction pool status report:
node1:
![txpool_node1](https://user-images.githubusercontent.com/46731787/71165370-b1fa7080-228b-11ea-899b-2ff0b2d724b3.png)

node2:
![txpool_node2](https://user-images.githubusercontent.com/46731787/71165380-b6268e00-228b-11ea-85b0-1bc70cb0440f.png)

node3:
![txpool_node3](https://user-images.githubusercontent.com/46731787/71165401-c0488c80-228b-11ea-938a-f8e1798c3e3d.png)

node4:
![txpool_node4](https://user-images.githubusercontent.com/46731787/71165427-c8a0c780-228b-11ea-9061-2f6080dc8e2e.png)

**Comment by WesleyLiu0717** [comment] 2019-12-19 10:38
3. trie 
The gcsize is growing from 0 to 600MB, I am not sure if it is normal.
node4:
![trie_node4](https://user-images.githubusercontent.com/46731787/71165901-9f346b80-228c-11ea-8b43-6112dc92154e.png)
4. INFO: some information about raft leader change
node4:
![info_1_node4](https://user-images.githubusercontent.com/46731787/71166079-f0445f80-228c-11ea-8de4-ccc144c6f6b8.png)
![info_2_node4](https://user-images.githubusercontent.com/46731787/71166085-f20e2300-228c-11ea-9a61-1555264e7c5a.png)
![info_3_node4](https://user-images.githubusercontent.com/46731787/71166090-f63a4080-228c-11ea-9bd5-b7ff278c8c26.png)
5. Dropping transaction propagation
This message occurs from 13:42:XX at each node.
node4:
![dropping_start_node4](https://user-images.githubusercontent.com/46731787/71166231-36012800-228d-11ea-98e1-629ede585deb.png)
6. fairness-exceeding 
This message occurs at 13:41:XX at each node
node4:
![fairness-exceeding](https://user-images.githubusercontent.com/46731787/71166494-d22b2f00-228d-11ea-9a8f-4239d6a3afc3.png)
Finally, this is the information of node 4 when it can't get the block
![node4](https://user-images.githubusercontent.com/46731787/71166741-52ea2b00-228e-11ea-9486-d006ef4e6ef3.jpg)

**Comment by trung** [comment] 2019-12-20 00:20
@WesleyLiu0717 thanks for the snapshots. Unfortunately it's hard to chain the events together with log fragments. I've been trying to reproduce the issue by flooding my network and with ~400K blocks, the issue has not been seen.

1.  Could you `grep` for `CRIT` in the log if there's any such event?
2.  Could you provide the logs from `13:44:xx` to the latest? If it's too verbose, maybe reduce `--verbosity` to 3 as I'm interested in the raft responsiveness
3. Could you paste the output of `geth version` from a running node?

**Comment by WesleyLiu0717** [comment] 2019-12-20 16:20
Hi @trung,
1. There is no event about "CRIT" in the log.
2. The log will be sorted out and given to you.
3. 
![image (6)](https://user-images.githubusercontent.com/46731787/71265717-c882f380-2381-11ea-8947-1bc572f23ef3.png)

Did you monitor the memory usage in the experiment ?
Has the memory usage ever decreased in your experiment?

In order to help you reproduce our experiment, we  put our code in the following link:
https://github.com/yujie0505/raft-test/blob/master/index.js

Npm module node-getopt and web3 have to be installed.

Two files are needed in this experiment:
1. privateKeys.json  If you want to send 100 tx/s, 100 private keys should put in this file.
```json
[
{
"private_key": "0xxxxxx"
},
{
"private_key": "0xxxxxx"
}
]
```
2. opt.json The node url and smart contract information
```json
{
"serv": {
"hosts":[
"ip1",
"ip2",
"ip3",
"ip4"
],
"ws_port": 8546
},
"smart_contract": {
"abi": [],
"address": "0xxxxxx"
}
} 
```

To do the experiment:

1. Deploy the smart contract (The simple storage version smart contract in the above discussion can be used.) and write the contract address into opt.json.
2. Run "node index.js -a 100 -c 0 -r 10800"
-a => The input rate of this experiment (-a 100 => 100 tx/s)
-c => Ignore it, set to  be 0.
-r => The duration "second" (-r 10800 => 3 hours)

Hope this will be helpful to you.
Many thanks!

**Comment by trung** [comment] 2019-12-20 17:05
@WesleyLiu0717 that's definitely very helpful. Thanks. I'll use it to run against my network.

Btw, from the version output, I can see that `geth` that you are using seems been built differently from our official version. You can find the binary distribution here: https://github.com/jpmorganchase/quorum/releases, and our official docker image here: https://hub.docker.com/u/quorumengineering

Here is the version i'm using:
```
Geth
Version: 1.8.18-stable
Git Commit: 20c95e5d836ebe94431ff5848e894dd938f4e147
Quorum Version: 2.4.0
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1337
Go Version: go1.11.13
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
```

Please give a try with our binaries.

**Comment by vsmk98** [comment] 2019-12-23 07:35
Hi @WesleyLiu0717, based on the `geth` start command you have shared, I have couple of suggestions:

- Can you set the blocktime to 250ms by using `--raftblocktime 250` in `geth` start command
- Also I notice that the txpool size used is default. suggest the following to be added to `geth` start command up ` --txpool.globalslots 50000 --txpool.accountslots 25000`

**Comment by WesleyLiu0717** [comment] 2019-12-23 10:11
@trung,
The log has been put in the following github repository,
and we do the experiment again with 200 tx/s for 2.5 hours.(It also stuck)
https://github.com/yujie0505/raft-test/tree/master/logs

The log is retrieved by the following instruction:
grep -P "(Imported|Mine)" log.simple-storage.200tps.3H.2019.12.19 > block-info
grep -P "(^raft)" log.simple-storage.200tps.3H.2019.12.19 > raft-info

@vsmk98  
I'm curious about the reason to adjust these two parameters.
1. We have adjusted raft block time to 1 second, more transactions can be included in a block.
But the memory still not decrease.
2. If 100 transactions from 100 different accounts can be confirmed in one second, it may not exceed the transaction pool limit.

**Comment by vsmk98** [comment] 2019-12-23 11:09
@WesleyLiu0717 - For the first one, I could not see that you had set the block period to a higher value and hence recommended. If you have set to  1 sec, I feel its good. Typically in my testing, I have seen raft performing better at block periods of 250 ms or more and avoid the leader re-election loop under high stress conditions. 
For 2nd one on the txpool size, agree that if everything gets confirmed with in 1 sec, it will never exceed the default value of 4096, however when running  the stress tests, what I have observed is, one or more nodes can lag behind the leader nodes (as can be seen from the logs you had shared earlier where the block number are out of sync across nodes). Once the node(s) starts lagging it can trigger re-election and while the re-election is happening, if transactions are continuously fired, it can fill up the transaction pool. Having a higher transaction pool size helps in such scenario.

**Comment by yujie0505** [comment] 2019-12-24 09:55
Hi @trung, it seems work after replacing the `geth` with the official one (the binary release on https://github.com/jpmorganchase/quorum/releases). We have conducted an experiment on it with the same setting for 1 hour, and it finally confirmed all transactions received and also decreased the memory usage to ~400M on each node. We are still going to do more testing on it. If the same issue occurs again, we will update here. 
Thank a lot for your help!

**Comment by yujie0505** [comment] 2019-12-24 10:23
Hi @vsmk98, I agree on your suggestions for better performance. However, in our previous testing, it would not release any memory in the whole testing period, even in the case that sending in a short time (10 minutes). Fortunately, it seems work after changing our `geth` version. We will work on it and update here if the same issue occurs again. Many thanks!

**Comment by vsmk98** [comment] 2019-12-27 06:02
I am closing this issue. Please reopen if you observe the issue again.

**Closed as completed by vsmk98** 2019-12-27 06:02 UTC
