### ISSUE TITLE
Add ability to get decrypted transaction input

### ISSUE THREAD

**Issue by paliwalg** [Consensys-Incorporated/quorum#121] opened 2017-05-24 13:26 UTC
I am trying to decode the input string returned from transaction for the simple storage contract set() function.
For a sample public transaction(contractobject.set(99)) input string is coming as 

0x6060604052341561000c57fe5b6040516020806100fa83398101604052515b60008190555b505b60c6806100346000396000f300606060405263ffffffff60e060020a6000350416632a1afcd98114603457806360fe47b11460535780636d4ce63c146065575bfe5b3415603b57fe5b60416084565b60408051918252519081900360200190f35b3415605a57fe5b6063600435608a565b005b3415606c57fe5b60416093565b60408051918252519081900360200190f35b60005481565b60008190555b50565b6000545b905600a165627a7a72305820dd78f3524b7023f728792f08d13c21b31c1c85f6e949db71bafe10ae2cbc75170029000000000000000000000000000000000000000000000000000000000000002a

I am not able to decode it using soliditycoder.decodeparams.

I am case of private transcations, for the same function call input string is coming as different all together.

Can you please check it out, is there something that's i am missing.

Thanks

**Comment by tylobban** [comment] 2017-05-24 14:48
@paliwalg hi, are you aware that the input string for private transactions is replaced with a hash of the encrypted payload, as described [here](https://github.com/jpmorganchase/quorum/wiki/Transaction-Processing#private-transaction-process-flow)? This is obviously important to ensure that no information is leaked about private transactions. (So it is expected, by design, that the input for a private transaction will be different to that of an equivalent public transaction).

**Comment by paliwalg** [comment] 2017-05-24 15:27
Agreed , but shouldn't input string be available on the node which is party for that transaction ? 
I can see logs are available for private transactions at node if that node is party for transaction, same should be the behavior for input field also.


Thanks

**Comment by paliwalg** [comment] 2017-05-26 08:49
Hi Tyrone,
Any updates on this ?
Or is there any other way to fetch the input string at the nodes which are party for that transaction ?

Thanks

**Comment by patrickmn** [comment] 2017-05-26 18:38
There's currently no way to get the decrypted input. Will keep this open as a feature request to track adding such a method.

**Comment by patrickmn** [comment] 2018-02-06 20:49
This will be addressed in https://github.com/jpmorganchase/quorum/issues/121

**Closed as completed by patrickmn** 2018-02-06 20:49 UTC
Labels: enhancement, privacy

**Comment by paliwalg** [comment] 2018-05-01 09:06
Did this enhancement got fixed in any of the release. I checked 2.0.1 and still the behaviors is same as before.
Any updates on this ?
