### ISSUE TITLE
 bug:Fatal: failed to read WAL: unexpected EOF

### ISSUE THREAD

**Issue by wenhuancai** [Consensys-Incorporated/quorum#712] opened 2019-05-13 08:21 UTC
I configured five nodes, and they worked.There was a blackout in the morning.I found this error on node 2.
![image](https://user-images.githubusercontent.com/20059816/57606110-cad6d100-759a-11e9-956f-0bf075417a9b.png)
Geth does not exist in the process.
![image](https://user-images.githubusercontent.com/20059816/57606181-f35ecb00-759a-11e9-8096-4b2474bb0275.png)
pm.wal = pm.replayWAL(maybeRaftSnapshot) is abnormal.
I don't think the program should continue at this point, which should be the exception handling, the program shouldn't continue

**Comment by wenhuancai** [comment] 2019-05-13 08:34
Second question: why are all my smart contracts gone.
![image](https://user-images.githubusercontent.com/20059816/57606966-9e23b900-759c-11e9-8473-9169076e6983.png)
Loaded most recent local full block  is zero?
why  Loaded most recent local fast block      number=334568 ?
The correct number of blocks should be 334568.
But I'm going to look it up now.
![image](https://user-images.githubusercontent.com/20059816/57607135-f6f35180-759c-11e9-8116-01208b8532c7.png)

**Comment by prd-fox** [comment] 2019-05-21 08:42
Hey.

It seems the root cause is that the upgrade to 1.8.12 introduced state caching, which means that state isn't written to disk immediately.
The way raft works means it requires the state to be written before committing the raft log, meaning the data was out of sync and couldn't recover.


Setting the `--gcmode=archive` option should fix the issue, and we will make sure that a raft node is always started with this flag in the future.

If you could try and let me know the results, that would be great.

**Comment by prd-fox** [comment] 2019-05-21 15:25
Related to https://github.com/jpmorganchase/quorum/issues/683

**Comment by wenhuancai** [comment] 2019-05-24 02:54
thank you.The mistake didn't happen.But I got a new error about when a lot of transactions are synchronized. @

#651

**Comment by prd-fox** [comment] 2019-05-24 08:46
Closing this as the main issue is solved. Can you open a new ticket for the issue you raised in #651, since that issue isn't related to raft. Thanks.

**Closed as completed by prd-fox** 2019-05-24 08:46 UTC
