### ISSUE TITLE
How to remove invalid transaction with "contract creation code storage out of gas" error

### ISSUE THREAD

**Issue by kigawas** [Consensys-Incorporated/quorum#1198] opened 2021-05-20 02:15 UTC
Every time deploying a contract to Node A (port 22000), Node B (port 22001) was also trying to execute some previous deployment but failed with "contract creation code storage out of gas" error.
But Node A still succeeded, so there's no actual harm.

#### Contract Code
```solidity
// SPDX-License-Identifier: MIT
pragma solidity >=0.4.22 <0.9.0;

contract Migrations {
    uint256 public last_completed_migration;
    address public owner;

    modifier restricted() {
        if (msg.sender == owner) _;
    }

    constructor() {
        owner = msg.sender;
    }

    function setCompleted(uint256 completed) public restricted {
        last_completed_migration = completed;
    }

    function upgrade(address new_address) public restricted {
        Migrations upgraded = Migrations(new_address);
        upgraded.setCompleted(last_completed_migration);
    }
}
```
Deployed with Remix IDE.

#### System information
Official docker container.

```bash
$ docker exec -it 85959869334f71cd1d6c9c2e4f930296896cb08bd1ff867a163a3d1164dcabec /bin/sh
/ # geth version
Geth
Version: 1.9.7-stable
Git Commit: a21e1d44cb4da8eaaf66dedb3ae16118db0cb7ef
Quorum Version: 21.1.0
Architecture: amd64
Protocol Versions: [64 63]
Network Id: 1337
Go Version: go1.15.5
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
```
Two nodes with istanbul BFT.

#### Expected behaviour
- No error
- Should only deployed to Node A

#### Actual behaviour

![image](https://user-images.githubusercontent.com/4182346/118907386-648ba280-b95a-11eb-92ca-a37ce435d1cd.png)

#### Steps to reproduce the behaviour
It's very subtle. Not sure how to reproduce.

#### Backtrace

No backtrace, just logs.

**Comment by nmvalera** [comment] 2021-07-13 14:02
@kigawas This seems to be related to the way the contract is compiled and not the node itself.

Can you make sure that you use the same Solidity pragma and solc version when compiling?

**Comment by kigawas** [comment] 2021-07-14 04:30
> @kigawas This seems to be related to the way the contract is compiled and not the node itself.
> 
> Can you make sure that you use the same Solidity pragma and solc version when compiling?

It happened when there are some failed contract deployment transactions on one node. Looks like not really related with solidity or solc, but related with the way to dispose of failed transactions.

A probable way to reproduce is to create contract deployment transactions with wrong nonce.

**Comment by nmvalera** [comment] 2021-07-20 06:53
@kigawas Thanks.

> A probable way to reproduce is to create contract deployment transactions with wrong nonce.

If sending a transaction with the wrong nonce we should get either "nonce too low" errors or see transactions pending forever.

If you are sure you are compiling the contract correctly (with compatible solc version and pragma). Then can you make sure that the gas limit set on the deployment transaction is high enough? Thanks!

**Comment by kigawas** [comment] 2021-07-20 07:16
> @kigawas Thanks.
> 
> > A probable way to reproduce is to create contract deployment transactions with wrong nonce.
> 
> If sending a transaction with the wrong nonce we should get either "nonce too low" errors or see transactions pending forever.
> 
> If you are sure you are compiling the contract correctly (with compatible solc version and pragma). Then can you make sure that the gas limit set on the deployment transaction is high enough? Thanks!

I don't think it's related with gas limit. My contracts are very simple ones (Box or Migration stuff you can find everywhere).

**Comment by antonydenyer** [comment] 2022-01-14 16:24
Is there any chance you could post your `genesis.json` for me?

**Comment by kigawas** [comment] 2022-01-15 01:39
> Is there any chance you could post your `genesis.json` for me?

Nothing special. Just used quorum wizard to generate

**Comment by baptiste-b-pegasys** [comment] 2022-01-17 15:05
I tested it with quick quick dev start and the contract, seems OK
![image](https://user-images.githubusercontent.com/85155432/149793643-2fc3b7a2-e926-41fe-9b85-78eee2955802.png)

**Comment by achraf17** [comment] 2022-01-27 09:11
closing this for now as unable to reproduce. Feel free to reopen.

**Closed as completed by achraf17** 2022-01-27 09:11 UTC
Labels: bug
