### ISSUE TITLE
Quorum v2.2.1  doesn't support DNS

### ISSUE THREAD

**Issue by abhayar** [Consensys-Incorporated/quorum#740] opened 2019-06-13 07:58 UTC
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `1.8.12-stable`

OS & Version: Linux 16.04

Release: `git status : HEAD detached at v2.2.1`

#### Expected behaviour
```
// ParseNode parses a node designator.
//
// There are two basic forms of node designators
//   - incomplete nodes, which only have the public key (node ID)
//   - complete nodes, which contain the public key and IP/Port information
//
// For incomplete nodes, the designator must look like one of these
//
//    enode://<hex node id>
//    <hex node id>
//
// For complete nodes, the node ID is encoded in the username portion
// of the URL, separated from the host by an @ sign. The hostname can
// be given as an IP address or a DNS domain name.
// The port in the host name section is the TCP listening port. If the
// TCP and UDP (discovery) ports differ, the UDP port is specified as
// query parameter "discport".
//
// In the following example, the node URL describes
// a node with IP address 10.3.58.6, TCP listening port 30303
// and UDP discovery port 30301.
//
//    enode://<hex node id>@10.3.58.6:30303?discport=30301
func ParseNode(rawurl string) (*Node, error) {
	if m := incompleteNodeURL.FindStringSubmatch(rawurl); m != nil {
		id, err := HexID(m[1])
		if err != nil {
			return nil, fmt.Errorf("invalid node ID (%v)", err)
		}
		return NewNode(id, nil, 0, 0), nil
	}
	return parseComplete(rawurl)
}

```
Above ParseNode ()function (from quorum v2.2.1) metioned it supports DNS

#### Actual behaviour
Quorum raft node is not started when DNS provided instead of IP

**Comment by prd-fox** [comment] 2019-06-13 10:27
What is the behaviour you are seeing?

Are transactions propagating but not blocks?
Are any nodes able to talk to each other, or is just a single node?

For what it's worth, v2.2.1 does have the DNS resolution code, but it seems like a regression was introduced with the 1.8.18 upgrade as upstream switched some files around, so there is a bug, but not with the version you are using (at least, not the *same* bug :) )

**Comment by prd-fox** [comment] 2019-06-13 10:48
This also seem to be raft specific.

I set up my network, using `localhost` instead of `127.0.0.1`, and worked fine for Istanbul - it converted the DNS name into the local IPv6 loopback address - but not for raft.

**Comment by prd-fox** [comment] 2019-06-13 10:57
Ok, looking a bit more, it seems that the raft-specific area is still expecting the IP address. If Quorum were to only run the ethereum p2p layer, then it would be fine, but alas, it does not.

I will look to make the changes and come back when I have a potential fix, if you are willing to try it.

**Comment by abhayar** [comment] 2019-06-13 11:25
@prd-fox  It just a single raft node. While starting node on aws using DNS, it throws constellation error,

```
panic: MustNew: Failed to connect to Constellation (qdata/ipa.ipc): lstat qdata/ipa.ipc: no such file or directory

goroutine 1 [running]:
github.com/ethereum/go-ethereum/private/constellation.MustNew(0xc42003400f, 0xd, 0xc42003400f)
	/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/private/constellation/constellation.go:109 +0x1dd
github.com/ethereum/go-ethereum/private.FromEnvironmentOrNil(0x10573da, 0xe, 0xc4202251a0, 0xc420225180)
	/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/private/private.go:20 +0x64

```
Instead of localhost , I used AWS DNS .

When I used localhost, node is started but for actual DNS it fails

**Comment by prd-fox** [comment] 2019-06-13 12:52
Ok. Is Constellation or Tessera running on the same machine?

Talking to the private transaction manager is only done over a unix socket, so DNS doesn't apply here. 

What was the behaviour you were expected? To be able to talk to the private transaction manager running on a different machine, over HTTP?

**Comment by abhayar** [comment] 2019-06-13 12:54
@prd-fox  constellation is running on same machine. I want both constellation and geth  running on  same machine.

**Comment by prd-fox** [comment] 2019-06-13 12:57
That is fine, and actually how it should work at the moment.
It seems that Quorum can't find the socket file when it's starting up.

Can you verify from the terminal that the file `qdata/ipa.ipc` exists?

**Comment by abhayar** [comment] 2019-06-13 12:58
@prd-fox  qdata/ipa.ipc file is exists. It is working on IP and localhost.

**Comment by prd-fox** [comment] 2019-06-13 13:00
Ok, if the file exists then quorum should be able to find it. Since it is a relative path, be certain that Quorum is also using the same relative path, or make it absolute.

Since this is a unix socket file, it has nothing to do with IP address or DNS names, so we can rule that out completely.

Restarting Constellation may also help solve the issue, if that is possible.

**Comment by abhayar** [comment] 2019-06-14 10:15
@prd-fox ,I tried with restarting node, error remains  same. But this issue faced only in case of DNS. On IP and localhost, quorum raft node is working fine.

**Comment by prd-fox** [comment] 2019-06-14 10:18
Can you list your Constellation and Quorum start commands?
And perhaps the last 20 or so lines from the Constellation log, please?

**Comment by abhayar** [comment] 2019-06-14 14:50
@prd-fox 
For constellation,
```
constellation-node ${NODENAME}.conf >> qdata/constellationLogs/constellation_${NODENAME}.log 2>&1 &
```
For geth ,
```
PRIVATE_CONFIG=qdata/$NODENAME.ipc geth --verbosity 6 --datadir qdata $GLOBAL_ARGS --rpccorsdomain "*" --raftport $RA_PORT --rpcport $R_PORT --port $W_PORT --ws --wsaddr 0.0.0.0 --wsport $WS_PORT --wsorigins '*' --wsapi $ENABLED_API 2>>qdata/gethLogs/${NODENAME}.log &
```

**Comment by prd-fox** [comment] 2019-06-14 15:08
Great, thanks.

What is the value of the property `socket` inside the constellation configuration file? I would expect it to be `ipa.ipc`.

My thinking is that if you are dynamically generating that file, based on DNS settings, then maybe there is some mismatch that is occurring.

**Comment by prd-fox** [comment] 2019-06-20 09:04
Hi Abhayar,

Any update on that Constellation config file? Somewhere there is a disconnect between the socket file that Constellation is creating and the one that Quorum is searching for.

**Comment by abhayar** [comment] 2019-06-20 10:37
@prd-fox, there in no mismatch between .conf file and ipa.ipc file  is also exists, In constellaction conf template when tls ="default" , this created .cert and .pem file for provided DNS. There might be mismatch between .cert  and .pem file , hence it is not working.

**Comment by prd-fox** [comment] 2019-06-20 10:59
Are you deleting the `.cert` and `.pem` files when changing the configuration?

**Comment by abhayar** [comment] 2019-06-20 11:09
Nope, I'm trying to run with same cert file , But getting below error while starting constellation node and  sending private transaction.

```
HandshakeFailed (Error_Protocol ("certificate rejected: Certificate validation failed",True,CertificateUnknown))
tail: inotify resources exhausted
```
and below are constellation error logs .

```
09:21:01 [INFO] Log level is LevelWarn
09:21:01 [WARN] tm.key is too accessible. Please run: chmod 0600 tm.key
09:21:01 [WARN] No TLS certificate or key found; generating tls-client-cert.pem/tls-client-key.pem
09:21:01 [WARN] No TLS certificate or key found; generating tls-server-cert.pem/tls-server-key.pem
HandshakeFailed (Error_Protocol ("certificate rejected: Certificate validation failed",True,CertificateUnknown))
HandshakeFailed (Error_Protocol ("certificate rejected: Certificate validation failed",True,CertificateUnknown))
HandshakeFailed (Error_Protocol ("certificate rejected: Certificate validation failed",True,CertificateUnknown))
09:21:04 [WARN] tls-known-clients (ca-or-tofu trust mode): Adding new fingerprint "4B:7F:38:C4:7E:84:D2:F9:2B:29:60:1F:FD:1D:B9:A9:D5:9A:5E:D2:66:40:A9:06:18:3C:EA:28:5A:D8:4B:2E:7A:5D:FC:B5:C7:58:6B:82:CF:EB:56:10:41:72:43:86:B9:18:9E:44:12:D6:DD:B7:C9:87:C8:E4:B8:00:BF:15" for host ipa-local.synechron.net
HandshakeFailed (Error_Protocol ("certificate rejected: Certificate validation failed",True,CertificateUnknown))
HandshakeFailed (Error_Protocol ("certificate rejected: Certificate validation failed",True,CertificateUnknown))
HandshakeFailed (Error_Protocol ("certificate rejected: Certificate validation failed",True,CertificateUnknown))
HandshakeFailed (Error_Protocol ("certificate rejected: Certificate validation failed",True,CertificateUnknown))
HandshakeFailed (Error_Protocol ("certificate rejected: Certificate validation failed",True,CertificateUnknown))
09:21:05 [WARN] tls-known-servers (ca-or-tofu trust mode): Adding new fingerprint "08:2D:8A:66:54:EE:A2:48:F0:E7:4F:9D:99:65:27:CB:47:C4:E9:0F:FA:CA:3A:2D:5F:FE:6F:10:A1:81:6E:89:F0:53:1B:75:17:49:F8:A3:49:9C:F6:EA:12:31:CD:F8:C4:28:01:EA:C9:41:72:C8:23:35:69:1C:72:A9:7C:B9" for host ipa-local.synechron.net
HandshakeFailed (Error_Protocol ("certificate rejected: Certificate validation failed",True,CertificateUnknown))
HandshakeFailed (Error_Protocol ("certificate rejected: Certificate validation failed",True,CertificateUnknown))
HandshakeFailed (Error_Protocol ("certificate rejected: Certificate validation failed",True,CertificateUnknown))
```

**Comment by prd-fox** [comment] 2019-06-20 12:26
I've spoken to one of my colleagues who is more familiar with TLS than myself. He says that if you are using the same certs then but with a different address (i.e. changing from `localhost` to the DNS address) then this is expected to produce a hostname verification failure, which lines up with the error in the logs.

Can you try removing the certs and starting afresh, using the DNS name from the start?

**Comment by abhayar** [comment] 2019-06-27 07:15
@prd-fox When tls is default, it creates certificates for  DNS  "ipa-local.synechron.net"  hence getting certificateUnknown error. Hence providing actual public DNS certificates . But getting below error.

```
10:30:39 [INFO] Log level is LevelWarn
10:30:39 [WARN] tm.key is too accessible. Please run: chmod 0600 tm.key
10:30:39 [WARN] tls-server-cert.pem's hostname (*.synechron.net) is different from the one given in the configuration (ipa-local.synechron.net). This may cause connection problems.
10:30:39 [WARN] tls-client-cert.pem's hostname (*.synechron.net) is different from the one given in the configuration (ipa-local.synechron.net). This may cause connection problems.
HandshakeFailed (Error_Misc "user error (unexpected type received. expecting handshake and got: Alert [(AlertLevel_Fatal,UnknownCa)])")

```
Getting same error also for selfsigned certifaicates for above DNS.

**Comment by namtruong** [comment] 2019-07-01 11:05
Hi - could you please send the full constellation config? Is `*.synechron.net` the cn of the certificate you generated or is this self-generated by constellation?

**Comment by abhayar** [comment] 2019-07-11 14:06
@namtruong  certificates are generated by us not by constellation, Even if constellation generates certificates, we are getting certificate unknown error.

Please find below constellation file.
```
CMD="constellation-node --url=https://127.0.0.$i:900$i/ --port=900$i --workdir=$DDIR --socket=tm.ipc --publickeys=tm.pub --privatekeys=tm.key --othernodes=https://127.0.0.1:9001/"
```

**Comment by namtruong** [comment] 2019-07-12 13:52
@abhayar the command above looks fine - however it seems to being using localhost instead of the dns.You mentioned couple of times above that the network started ok for localhost but not dns - are you now saying you're seeing certificate unknown for both scenarios?

Could you provide more details on each config used (either dns or localhost - please provide full config file and commands, etc...), and the associated full error log messages etc...? The full details provided will help us replicate the issue and resolve it as soon as we can

**Comment by namtruong** [comment] 2019-07-12 14:07
As this issue is likely to be more specific to constellation with tls and dns config - I will now close this issue as the title is misleading.

Please raise an issue in constellation repo https://github.com/jpmorganchase/constellation with the details requested above and I will take a look.

Thanks

**Closed as completed by namtruong** 2019-07-12 14:07 UTC
Labels: bug
