### ISSUE TITLE
"Impossible reorg, please file an issue"

### ISSUE THREAD

**Issue by stevenroose** [Consensys-Incorporated/quorum#389] opened 2018-05-31 12:41 UTC
```
ERROR[05-31|08:40:07] Impossible reorg, please file an issue   oldnum=17557 oldhash=662e4e…493660 newnum=17557 newhash=662e4e…493660
```

**Comment by jpmsam** [comment] 2018-05-31 20:09
@stevenroose can you please provide more details on the version you were running and which consensus?

**Comment by stevenroose** [comment] 2018-06-01 08:21
Latest master branch at the time of writing. We have an Istanbul cluster with 3 validators. We notice that the clocks of the machines are out of sync for like 1 minute between the earliest en latest. They are just AWS machines, though. 

We also f.e. get warnings on the earliest machine that the block the latest machine makes are "future blocks". You can see in the log message that it's trying to reorg from and towards the exact same block. The fact that that fails is logical, it should not attempt to do that. It looks like a block creator gets back his own block and gets confused.

**Comment by stevenroose** [comment] 2018-06-04 13:54
This got solves as soon as we solved https://github.com/jpmorganchase/quorum/issues/385.

**Comment by kubasiemion** [comment] 2018-06-14 13:06
Nope, the problem is back.

**Comment by kevinlaiyh** [comment] 2018-07-25 21:06
Found the similar problem [#14833](https://github.com/ethereum/go-ethereum/issues/14833) on ethereum.

**Comment by vietlq** [comment] 2018-12-05 13:09
> We have an Istanbul cluster with 3 validators.

@stevenroose For BFT you need to have `N = 3f + 1`, means you need at least 4 nodes to have minimum valid number of nodes to run Istanbul BFT. In this case you need `N - f = 4 - 1 = 3` validators to agree on one hash to make it viable. If you have fewer than 4 validators, you are asking for trouble.

**Comment by vietlq** [comment] 2018-12-07 06:18
I can reproduce the issue simply by running the 7nodes example. The error will occur rather quickly within few minutes of running. I observed that the `oldhash` & `newhash` are the same:

```
$ for i in $(seq 1 7); do echo Node ${i}; docker logs quorum-examples_node${i}_1 2>&1 | grep ^ERR; done
Node 1
ERROR[12-07|06:03:05] Impossible reorg, please file an issue   oldnum=59 oldhash=e43af9…398633 newnum=59 newhash=e43af9…398633
ERROR[12-07|06:04:08] Impossible reorg, please file an issue   oldnum=122 oldhash=dd3c92…49d309 newnum=122 newhash=dd3c92…49d309
ERROR[12-07|06:07:03] Impossible reorg, please file an issue   oldnum=297 oldhash=39bc33…e55cfa newnum=297 newhash=39bc33…e55cfa
ERROR[12-07|06:07:24] Impossible reorg, please file an issue   oldnum=318 oldhash=bd2f50…f82697 newnum=318 newhash=bd2f50…f82697
Node 2
ERROR[12-07|06:03:00] Impossible reorg, please file an issue   oldnum=54 oldhash=d46e6a…339d39 newnum=54 newhash=d46e6a…339d39
ERROR[12-07|06:03:14] Impossible reorg, please file an issue   oldnum=68 oldhash=e140dc…ecd34e newnum=68 newhash=e140dc…ecd34e
ERROR[12-07|06:05:55] Impossible reorg, please file an issue   oldnum=229 oldhash=8991a5…fec54a newnum=229 newhash=8991a5…fec54a
ERROR[12-07|06:06:23] Impossible reorg, please file an issue   oldnum=257 oldhash=7d81d4…8b642e newnum=257 newhash=7d81d4…8b642e
ERROR[12-07|06:13:23] Impossible reorg, please file an issue   oldnum=677 oldhash=3a21df…6b6df3 newnum=677 newhash=3a21df…6b6df3
ERROR[12-07|06:14:19] Impossible reorg, please file an issue   oldnum=733 oldhash=36b8de…cbfb94 newnum=733 newhash=36b8de…cbfb94
Node 3
ERROR[12-07|06:03:41] Impossible reorg, please file an issue   oldnum=95 oldhash=b744ad…f3d60c newnum=95 newhash=b744ad…f3d60c
ERROR[12-07|06:04:09] Impossible reorg, please file an issue   oldnum=123 oldhash=bf1efe…193324 newnum=123 newhash=bf1efe…193324
ERROR[12-07|06:08:00] Impossible reorg, please file an issue   oldnum=354 oldhash=a64bf5…68cf20 newnum=354 newhash=a64bf5…68cf20
ERROR[12-07|06:13:29] Impossible reorg, please file an issue   oldnum=683 oldhash=3cb381…7b1615 newnum=683 newhash=3cb381…7b1615
ERROR[12-07|06:14:18] Impossible reorg, please file an issue   oldnum=732 oldhash=97eb8a…faad97 newnum=732 newhash=97eb8a…faad97
ERROR[12-07|06:14:46] Impossible reorg, please file an issue   oldnum=760 oldhash=1cfe76…97b3e0 newnum=760 newhash=1cfe76…97b3e0
Node 4
ERROR[12-07|06:03:16] Impossible reorg, please file an issue   oldnum=70 oldhash=fea7bc…766aef newnum=70 newhash=fea7bc…766aef
ERROR[12-07|06:09:41] Impossible reorg, please file an issue   oldnum=455 oldhash=e25c2a…603ba9 newnum=455 newhash=e25c2a…603ba9
ERROR[12-07|06:13:39] Impossible reorg, please file an issue   oldnum=693 oldhash=4c6d95…849333 newnum=693 newhash=4c6d95…849333
ERROR[12-07|06:14:28] Impossible reorg, please file an issue   oldnum=742 oldhash=302daf…084565 newnum=742 newhash=302daf…084565
ERROR[12-07|06:16:13] Impossible reorg, please file an issue   oldnum=847 oldhash=9eed89…bd6410 newnum=847 newhash=9eed89…bd6410
Node 5
ERROR[12-07|06:03:25] Impossible reorg, please file an issue   oldnum=79 oldhash=fbe5ce…41abbb newnum=79 newhash=fbe5ce…41abbb
ERROR[12-07|06:07:51] Impossible reorg, please file an issue   oldnum=345 oldhash=bf7135…b804dd newnum=345 newhash=bf7135…b804dd
ERROR[12-07|06:08:26] Impossible reorg, please file an issue   oldnum=380 oldhash=7e50b6…079f73 newnum=380 newhash=7e50b6…079f73
ERROR[12-07|06:14:16] Impossible reorg, please file an issue   oldnum=730 oldhash=18cf8a…b18449 newnum=730 newhash=18cf8a…b18449
Node 6
ERROR[12-07|06:02:40] Impossible reorg, please file an issue   oldnum=34 oldhash=fbf848…4d8cf8 newnum=34 newhash=fbf848…4d8cf8
ERROR[12-07|06:05:07] Impossible reorg, please file an issue   oldnum=181 oldhash=72554a…27077d newnum=181 newhash=72554a…27077d
ERROR[12-07|06:11:46] Impossible reorg, please file an issue   oldnum=580 oldhash=93e492…f2c77d newnum=580 newhash=93e492…f2c77d
ERROR[12-07|06:15:16] Impossible reorg, please file an issue   oldnum=790 oldhash=da30d6…c3b204 newnum=790 newhash=da30d6…c3b204
ERROR[12-07|06:16:05] Impossible reorg, please file an issue   oldnum=839 oldhash=ad292e…d2347a newnum=839 newhash=ad292e…d2347a
Node 7
ERROR[12-07|06:07:57] Impossible reorg, please file an issue   oldnum=351 oldhash=cddf5a…17222c newnum=351 newhash=cddf5a…17222c
ERROR[12-07|06:15:46] Impossible reorg, please file an issue   oldnum=820 oldhash=317f62…073a3a newnum=820 newhash=317f62…073a3a
```

Probably can be fixed by https://github.com/jpmorganchase/quorum/pull/539 for the cases when hashes are the same. I'm not sure about the cases when hashes are different (not observed yet).

**Closed as completed** 2019-02-12 23:51 UTC
Labels: bug, consensus | IBFT
