### ISSUE TITLE
Use the permissioned nodes for discovery

### ISSUE THREAD

**Issue by stevenroose** [Consensys-Incorporated/quorum#287] opened 2018-02-16 11:14 UTC
The usage of a permissioned network with `--permissioned` and the `permissioned-nodes.json` file, should make it unnecessary to have bootnodes. Nodes should use this list as the initial source of new peers instead of bootnodes.

**Comment by stevenroose** [comment] 2018-02-16 11:46
So with Istanbul, it seems that when `--mine` is provided, peers actually already do this. However, I struggle to get my non-mining peers to join. When I force them (from either side) to add a peer, they start syncing fine, but without a manual trigger, they stay stale.

**Comment by Open-Rawi** [comment] 2019-06-23 17:44
Hi @fixanoid can we close this issue , this is a dupe of #378

**Closed as completed** 2021-03-26 15:27 UTC
Labels: enhancement, core, good first issue, backlog
