### ISSUE TITLE
Data sync not happening between nodes deployed on different machines

### ISSUE THREAD

**Issue by sivachaitanya** [Consensys-Incorporated/quorum#171] opened 2017-09-03 06:05 UTC
#### System information

Geth version: Geth/v1.5.0-unstable/linux/go1.6.2

OS & Version: Linux

Branch, Commit Hash or Release: `git status`

#### Expected behaviour
I should be able to read data from both node 1 and node 3

#### Actual behaviour
I am able to read data from node 1 where I've added the data, but executing eth.getTransaction(txhash) gives me null which meas node 3 hasnt synced node 1 data. All of this is a public transaction

#### Steps to reproduce the behaviour

I have boot node and node 1 deployed on one machine as block maker and voter and relevant invoking tm2.conf file looks like -
```

url = "http://10.10.10.5:9000/"
port = 9000
socketPath = "qdata/tm2.ipc"
otherNodeUrls = []
publicKeyPath = "keys/tm2.pub"
privateKeyPath = "keys/tm2.key"
archivalPublicKeyPath = "keys/tm2a.pub"
archivalPrivateKeyPath = "keys/tm2a.key"
storagePath = "qdata/constellation2"

```
and node3 deployed on another machine which is ONLY voter and uses tm5.conf which config looks like - 

```
url = "http://10.11.11.4:9000/"
port = 9000
socketPath = "qdata/tm5.ipc"
otherNodeUrls = ["http://10.10.10.5:9000/"]
publicKeyPath = "keys/tm5.pub"
privateKeyPath = "keys/tm5.key"
archivalPublicKeyPath = "keys/tm5a.pub"
archivalPrivateKeyPath = "keys/tm5a.key"
storagePath = "qdata/constellation5"
```

both the nodes constellations logs show no errors. In the  constellation log for node 1 the log is displayed as - 
```

nohup: appending output to 'nohup.out'
2017 Sep-03 05:24:32216663 [INFO] Constellation initializing using config file tm2.conf
2017 Sep-03 05:24:32217548 [INFO] Log level is LevelDebug
2017 Sep-03 05:24:32217620 [INFO] Utilizing 2 core(s)
2017 Sep-03 05:24:32220587 [INFO] Constructing Enclave using keypairs (keys/tm2.pub, keys/tm2.key) (keys/tm2a.pub, keys/tm2a.key)
2017 Sep-03 05:24:32220802 [INFO] Initializing storage qdata/constellation2
2017 Sep-03 05:24:32276282 [INFO] Internal API listening on qdata/tm2.ipc
2017 Sep-03 05:24:32276271 [INFO] External API listening on port 9000
2017 Sep-03 05:24:32276219 [INFO] Node started
2017 Sep-03 05:24:38344272 [DEBUG] Request from : ApiUpcheck; Response: ApiUpcheckR
2017 Sep-03 05:25:09751069 [DEBUG] Request from 10.11.11.4:49940: ApiPartyInfo (PartyInfo {piUrl = "http://10.11.11.4:9000/", piRcpts = fromList [("R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju/1xkY=","http://10.11.11.4:9000/")], piParties = fromList ["http://10.10.10.5:9000/"]}); Response: ApiPartyInfoR (PartyInfo {piUrl = "http://10.10.10.5:9000/", piRcpts = fromList [("QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc=","http://10.10.10.5:9000/"),("R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju/1xkY=","http://10.11.11.4:9000/")], piParties = fromList ["http://10.10.10.5:9000/"]})
2017 Sep-03 05:29:35051830 [DEBUG] Request from 10.10.10.5:48254: ApiPartyInfo (PartyInfo {piUrl = "http://10.10.10.5:9000/", piRcpts = fromList [("QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc=","http://10.10.10.5:9000/"),("R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju/1xkY=","http://10.11.11.4:9000/")], piParties = fromList ["http://10.10.10.5:9000/"]}); Response: ApiPartyInfoR (PartyInfo {piUrl = "http://10.10.10.5:9000/", piRcpts = fromList [("QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc=","http://10.10.10.5:9000/"),("R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju/1xkY=","http://10.11.11.4:9000/")], piParties = fromList ["http://10.10.10.5:9000/"]})
2017 Sep-03 05:30:09760130 [DEBUG] Request from 10.11.11.4:50490: ApiPartyInfo (PartyInfo {piUrl = "http://10.11.11.4:9000/", piRcpts = fromList [("QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc=","http://10.10.10.5:9000/"),("R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju/1xkY=","http://10.11.11.4:9000/")], piParties = fromList ["http://10.10.10.5:9000/"]}); Response: ApiPartyInfoR (PartyInfo {piUrl = "http://10.10.10.5:9000/", piRcpts = fromList [("QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc=","http://10.10.10.5:9000/"),("R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju/1xkY=","http://10.11.11.4:9000/")], piParties = fromList ["http://10.10.10.5:9000/"]})
2017 Sep-03 05:34:37725427 [DEBUG] Request from 10.10.10.5:49104: ApiPartyInfo (PartyInfo {piUrl = "http://10.10.10.5:9000/", piRcpts = fromList [("QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc=","http://10.10.10.5:9000/"),("R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju/1xkY=","http://10.11.11.4:9000/")], piParties = fromList ["http://10.10.10.5:9000/"]}); Response: ApiPartyInfoR (PartyInfo {piUrl = "http://10.10.10.5:9000/", piRcpts = fromList [("QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc=","http://10.10.10.5:9000/"),("R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju/1xkY=","http://10.11.11.4:9000/")], piParties = fromList ["http://10.10.10.5:9000/"]})
2017 Sep-03 05:35:09798877 [DEBUG] Request from 10.11.11.4:51044: ApiPartyInfo (PartyInfo {piUrl = "http://10.11.11.4:9000/", piRcpts = fromList [("QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc=","http://10.10.10.5:9000/"),("R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju/1xkY=","http://10.11.11.4:9000/")], piParties = fromList ["http://10.10.10.5:9000/"]}); Response: ApiPartyInfoR (PartyInfo {piUrl = "http://10.10.10.5:9000/", piRcpts = fromList [("QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc=","http://10.10.10.5:9000/"),("R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju/1xkY=","http://10.11.11.4:9000/")], piParties = fromList ["http://10.10.10.5:9000/"]})
2017 Sep-03 05:39:40398721 [DEBUG] Request from 10.10.10.5:49964: ApiPartyInfo (PartyInfo {piUrl = "http://10.10.10.5:9000/", piRcpts = fromList [("QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc=","http://10.10.10.5:9000/"),("R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju/1xkY=","http://10.11.11.4:9000/")], piParties = fromList ["http://10.10.10.5:9000/"]}); Response: ApiPartyInfoR (PartyInfo {piUrl = "http://10.10.10.5:9000/", piRcpts = fromList [("QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc=","http://10.10.10.5:9000/"),("R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju/1xkY=","http://10.11.11.4:9000/")], piParties = fromList ["http://10.10.10.5:9000/"]})
2017 Sep-03 05:40:09837242 [DEBUG] Request from 10.11.11.4:51600: ApiPartyInfo (PartyInfo {piUrl = "http://10.11.11.4:9000/", piRcpts = fromList [("QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc=","http://10.10.10.5:9000/"),("R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju/1xkY=","http://10.11.11.4:9000/")], piParties = fromList ["http://10.10.10.5:9000/"]}); Response: ApiPartyInfoR (PartyInfo {piUrl = "http://10.10.10.5:9000/", piRcpts = fromList [("QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc=","http://10.10.10.5:9000/"),("R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju/1xkY=","http://10.11.11.4:9000/")], piParties = fromList ["http://10.10.10.5:9000/"]})
2017 Sep-03 05:44:42984722 [DEBUG] Request from 10.10.10.5:50820: ApiPartyInfo (PartyInfo {piUrl = "http://10.10.10.5:9000/", piRcpts = fromList [("QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc=","http://10.10.10.5:9000/"),("R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju/1xkY=","http://10.11.11.4:9000/")], piParties = fromList ["http://10.10.10.5:9000/"]}); Response: ApiPartyInfoR (PartyInfo {piUrl = "http://10.10.10.5:9000/", piRcpts = fromList [("QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc=","http://10.10.10.5:9000/"),("R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju/1xkY=","http://10.11.11.4:9000/")], piParties = fromList ["http://10.10.10.5:9000/"]})

```

and node 3 constellation log shown as - 

```
nohup: appending output to 'nohup.out'
2017 Sep-03 05:25:09524816 [INFO] Constellation initializing using config file tm5.conf
2017 Sep-03 05:25:09528401 [INFO] Log level is LevelDebug
2017 Sep-03 05:25:09528491 [INFO] Utilizing 2 core(s)
2017 Sep-03 05:25:09528924 [INFO] Constructing Enclave using keypairs (keys/tm5.pub, keys/tm5.key) (keys/tm5a.pub, keys/tm5a.key)
2017 Sep-03 05:25:09529209 [INFO] Initializing storage qdata/constellation5
2017 Sep-03 05:25:09606851 [INFO] External API listening on port 9000
2017 Sep-03 05:25:09606862 [INFO] Internal API listening on qdata/tm5.ipc
2017 Sep-03 05:25:09606804 [INFO] Node started
~
```

So the problem here is, I am able to deploy contract and add data using contract functions in node 1, however pointing to node3 and calling the same function on contract address of node 1 gives me back null. Transactions are not synced between the nodes I guess ?. And here I am performing public transaction so all the participating should be able to see and read the data? but thats not happening in node 3 case, can somebody please help me resolve this.

cute pic - 
https://www.instagram.com/p/BYGgz26BuZA/?hl=en&taken-by=utamaruru

**Comment by patrickmn** [comment] 2017-09-04 17:33
Duplicate of https://github.com/jpmorganchase/quorum-examples/issues/39

**Closed as completed by patrickmn** 2017-09-04 17:33 UTC
Labels: duplicate
